#!/usr/bin/env bash
# Installs the §7.5B native-messaging host (extension_api/native_host.py)
# for one or more browsers, per the roadmap's Phase B plan.
#
# A native messaging host can only ever be launched by an extension ID that
# is explicitly listed in the host's own manifest — that allowlist IS the
# security boundary (no bridge token needed, unlike §7.5A's HTTP transport).
# This means you must know your extension's ID (visible at chrome://extensions
# or about:debugging#/runtime/this-firefox with Developer Mode/temporary
# loading enabled) before running this script.
#
# Usage:
#   desktop/linux/scripts/install_native_host.sh <extension-id> [browser ...]
#
#   browser is one of: chrome chromium brave edge firefox (default: all of
#   the Chromium-family ones auto-detected as installed, plus firefox).
#
# Examples:
#   desktop/linux/scripts/install_native_host.sh abcdefghijklmnopqrstuvwxyzabcdef chrome
#   desktop/linux/scripts/install_native_host.sh my-extension@example.com firefox

set -euo pipefail

TOOLKIT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
HOST_NAME="com.imagetoolkit.bridge"
LAUNCHER="$TOOLKIT_ROOT/desktop/linux/scripts/run_native_host.sh"

if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <extension-id> [browser ...]" >&2
    echo "  browser: chrome | chromium | brave | edge | firefox (default: autodetect)" >&2
    exit 1
fi

EXT_ID="$1"
shift || true
BROWSERS=("$@")

if [ ! -x "$LAUNCHER" ]; then
    cat > "$LAUNCHER" <<LAUNCHER_EOF
#!/usr/bin/env bash
# Auto-generated by install_native_host.sh — do not edit directly.
set -e
cd "$TOOLKIT_ROOT"
source .venv/bin/activate
exec python -m extension_api.native_host
LAUNCHER_EOF
    chmod +x "$LAUNCHER"
    echo "[install_native_host] Wrote launcher: $LAUNCHER"
fi

write_manifest() {
    local dest_dir="$1"
    local key="$2"     # "allowed_origins" (Chromium) or "allowed_extensions" (Firefox)
    local value="$3"   # the formatted JSON array entry
    mkdir -p "$dest_dir"
    local dest="$dest_dir/$HOST_NAME.json"
    cat > "$dest" <<MANIFEST_EOF
{
  "name": "$HOST_NAME",
  "description": "Image Toolkit native messaging bridge (§7.5B)",
  "path": "$LAUNCHER",
  "type": "stdio",
  "$key": [$value]
}
MANIFEST_EOF
    echo "[install_native_host] Installed: $dest"
}

if [ "${#BROWSERS[@]}" -eq 0 ]; then
    [ -d "$HOME/.config/google-chrome" ] && BROWSERS+=("chrome")
    [ -d "$HOME/.config/chromium" ] && BROWSERS+=("chromium")
    [ -d "$HOME/.config/BraveSoftware" ] && BROWSERS+=("brave")
    [ -d "$HOME/.config/microsoft-edge" ] && BROWSERS+=("edge")
    [ -d "$HOME/.mozilla" ] && BROWSERS+=("firefox")
    if [ "${#BROWSERS[@]}" -eq 0 ]; then
        echo "No known browser config directories found; specify browsers explicitly." >&2
        exit 1
    fi
    echo "[install_native_host] Autodetected browsers: ${BROWSERS[*]}"
fi

CHROMIUM_ORIGIN="\"chrome-extension://$EXT_ID/\""

for browser in "${BROWSERS[@]}"; do
    case "$browser" in
        chrome)
            write_manifest "$HOME/.config/google-chrome/NativeMessagingHosts" "allowed_origins" "$CHROMIUM_ORIGIN"
            ;;
        chromium)
            write_manifest "$HOME/.config/chromium/NativeMessagingHosts" "allowed_origins" "$CHROMIUM_ORIGIN"
            ;;
        brave)
            # Brave reads the Chrome NativeMessagingHosts location, not its own —
            # documented quirk, see moon/roadmaps/extension.md §7.13.
            write_manifest "$HOME/.config/google-chrome/NativeMessagingHosts" "allowed_origins" "$CHROMIUM_ORIGIN"
            ;;
        edge)
            write_manifest "$HOME/.config/microsoft-edge/NativeMessagingHosts" "allowed_origins" "$CHROMIUM_ORIGIN"
            ;;
        firefox)
            write_manifest "$HOME/.mozilla/native-messaging-hosts" "allowed_extensions" "\"$EXT_ID\""
            ;;
        *)
            echo "Unknown browser: $browser (expected chrome|chromium|brave|edge|firefox)" >&2
            exit 1
            ;;
    esac
done

echo "[install_native_host] Done. Reload the extension and re-check its native-messaging status in the options page."
