"""
backend/src/models/full_finetune.py
=====================================
Full SDXL checkpoint fine-tuning with DeepSpeed ZeRO-2/3 offload.

Recommended VRAM budgets (1024², BF16, xformers, grad-ckpt):
  ZeRO-2 + CPU optimizer offload on RTX 3090 Ti 24 GB: batch 1, ga 8
  ZeRO-3 + CPU offload on RTX 4080 16 GB:              batch 1, ga 4 (~3× slower)

The FullFineTuner selectively freezes the VAE and optionally the first two
down_blocks and both text encoders to fit within 24 GB.

Usage
-----
    cfg = FullFTConfig(base_model_path="Laxhar/noobai-XL-Vpred-1.0")
    ft = FullFineTuner(cfg)
    ft.train(dataloader)
"""

from __future__ import annotations
from .full_fine_tuner import FullFineTuner

import os
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import torch
import torch.nn.functional as F
from accelerate import Accelerator
from diffusers import (
    AutoencoderKL,
    DDPMScheduler,
    UNet2DConditionModel,
)
from diffusers.optimization import get_scheduler
from diffusers.training_utils import EMAModel, compute_snr
from torch.utils.data import DataLoader
from transformers import CLIPTextModel, CLIPTextModelWithProjection, CLIPTokenizer
from tqdm.auto import tqdm

try:
    import bitsandbytes as bnb
    _BNB_OK = True
except ImportError:
    _BNB_OK = False

try:
    from transformers.optimization import Adafactor
    _ADAFACTOR_OK = True
except ImportError:
    _ADAFACTOR_OK = False

@dataclass
class FullFTConfig:
    base_model_path: str = "Laxhar/noobai-XL-Vpred-1.0"
    prediction_type: str = "v_prediction"
    zero_terminal_snr: bool = True

    # Freezing strategy
    freeze_text_encoders: bool = True
    freeze_down_blocks: int = 0        # freeze first N down_blocks (0 = none)

    # Training hyper-params
    resolution: int = 1024
    train_batch_size: int = 1
    gradient_accumulation_steps: int = 8
    gradient_checkpointing: bool = True
    mixed_precision: str = "bf16"
    max_train_steps: int = 12000
    snr_gamma: Optional[float] = 1.0  # 1.0 for v-pred, 5.0 for ε

    # Optimizer
    optimizer_type: str = "adamw8bit"
    learning_rate: float = 1e-6
    weight_decay: float = 1e-2
    lr_scheduler: str = "cosine"
    lr_warmup_steps: int = 500

    # EMA
    use_ema: bool = True
    ema_decay: float = 0.9999

    # DeepSpeed config path (generated by accelerate config)
    deepspeed_config: Optional[str] = None

    # Output
    output_dir: str = "output_full_ft"
    save_every_n_steps: int = 1000

