"""
backend/src/models/full_finetune.py
=====================================
Full SDXL checkpoint fine-tuning with DeepSpeed ZeRO-2/3 offload.

Recommended VRAM budgets (1024², BF16, xformers, grad-ckpt):
  ZeRO-2 + CPU optimizer offload on RTX 3090 Ti 24 GB: batch 1, ga 8
  ZeRO-3 + CPU offload on RTX 4080 16 GB:              batch 1, ga 4 (~3× slower)

The FullFineTuner selectively freezes the VAE and optionally the first two
down_blocks and both text encoders to fit within 24 GB.

Usage
-----
    cfg = FullFTConfig(base_model_path="Laxhar/noobai-XL-Vpred-1.0")
    ft = FullFineTuner(cfg)
    ft.train(dataloader)
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

import torch
import torch.nn.functional as F
from accelerate import Accelerator
from diffusers import (
    AutoencoderKL,
    DDPMScheduler,
    DPMSolverMultistepScheduler,
    StableDiffusionXLPipeline,
    UNet2DConditionModel,
)
from diffusers.optimization import get_scheduler
from diffusers.training_utils import EMAModel, compute_snr
from torch.utils.data import DataLoader
from transformers import CLIPTextModel, CLIPTextModelWithProjection, CLIPTokenizer
from tqdm.auto import tqdm

try:
    import bitsandbytes as bnb
    _BNB_OK = True
except ImportError:
    _BNB_OK = False

try:
    from transformers.optimization import Adafactor
    _ADAFACTOR_OK = True
except ImportError:
    _ADAFACTOR_OK = False


@dataclass
class FullFTConfig:
    base_model_path: str = "Laxhar/noobai-XL-Vpred-1.0"
    prediction_type: str = "v_prediction"
    zero_terminal_snr: bool = True

    # Freezing strategy
    freeze_text_encoders: bool = True
    freeze_down_blocks: int = 0        # freeze first N down_blocks (0 = none)

    # Training hyper-params
    resolution: int = 1024
    train_batch_size: int = 1
    gradient_accumulation_steps: int = 8
    gradient_checkpointing: bool = True
    mixed_precision: str = "bf16"
    max_train_steps: int = 12000
    snr_gamma: Optional[float] = 1.0  # 1.0 for v-pred, 5.0 for ε

    # Optimizer
    optimizer_type: str = "adamw8bit"
    learning_rate: float = 1e-6
    weight_decay: float = 1e-2
    lr_scheduler: str = "cosine"
    lr_warmup_steps: int = 500

    # EMA
    use_ema: bool = True
    ema_decay: float = 0.9999

    # DeepSpeed config path (generated by accelerate config)
    deepspeed_config: Optional[str] = None

    # Output
    output_dir: str = "output_full_ft"
    save_every_n_steps: int = 1000


class FullFineTuner:
    """Full SDXL fine-tuning with selective freezing and optional EMA."""

    def __init__(self, cfg: FullFTConfig):
        self.cfg = cfg
        os.makedirs(cfg.output_dir, exist_ok=True)

        self.accelerator = Accelerator(
            gradient_accumulation_steps=cfg.gradient_accumulation_steps,
            mixed_precision=cfg.mixed_precision,
        )

        print(f"[FullFineTuner] Loading {cfg.base_model_path}")
        self._load_components()
        self._apply_freezing()
        self.ema: Optional[EMAModel] = None

    # ------------------------------------------------------------------
    def _load_components(self):
        cfg = self.cfg
        self.tokenizer_one = CLIPTokenizer.from_pretrained(cfg.base_model_path, subfolder="tokenizer")
        self.tokenizer_two = CLIPTokenizer.from_pretrained(cfg.base_model_path, subfolder="tokenizer_2")
        self.text_encoder_one = CLIPTextModel.from_pretrained(cfg.base_model_path, subfolder="text_encoder")
        self.text_encoder_two = CLIPTextModelWithProjection.from_pretrained(cfg.base_model_path, subfolder="text_encoder_2")
        self.vae = AutoencoderKL.from_pretrained(cfg.base_model_path, subfolder="vae")
        self.unet = UNet2DConditionModel.from_pretrained(cfg.base_model_path, subfolder="unet")
        self.noise_scheduler = DDPMScheduler.from_pretrained(cfg.base_model_path, subfolder="scheduler")

        if cfg.prediction_type == "v_prediction":
            self.noise_scheduler.config.prediction_type = "v_prediction"
            if cfg.zero_terminal_snr:
                self.noise_scheduler.config.rescale_betas_zero_snr = True

        if cfg.gradient_checkpointing:
            self.unet.enable_gradient_checkpointing()

    def _apply_freezing(self):
        cfg = self.cfg
        # VAE is always frozen
        self.vae.requires_grad_(False)
        self.vae.to(self.accelerator.device)

        if cfg.freeze_text_encoders:
            self.text_encoder_one.requires_grad_(False)
            self.text_encoder_two.requires_grad_(False)
            self.text_encoder_one.to(self.accelerator.device)
            self.text_encoder_two.to(self.accelerator.device)

        # Selective UNet freezing: first N down_blocks
        for i in range(cfg.freeze_down_blocks):
            prefix = f"down_blocks.{i}."
            for name, p in self.unet.named_parameters():
                if name.startswith(prefix):
                    p.requires_grad_(False)

        trainable = sum(p.numel() for p in self.unet.parameters() if p.requires_grad)
        total = sum(p.numel() for p in self.unet.parameters())
        print(f"  UNet trainable: {trainable / 1e6:.1f}M / {total / 1e6:.1f}M params")

    # ------------------------------------------------------------------
    def _build_optimizer(self):
        params = [p for p in self.unet.parameters() if p.requires_grad]
        name = self.cfg.optimizer_type.lower()
        lr = self.cfg.learning_rate

        if name == "adamw":
            return torch.optim.AdamW(params, lr=lr, weight_decay=self.cfg.weight_decay)
        if name == "adamw8bit":
            if not _BNB_OK:
                raise ImportError("bitsandbytes required")
            return bnb.optim.AdamW8bit(params, lr=lr, weight_decay=self.cfg.weight_decay)
        if name == "lion":
            if not _BNB_OK:
                raise ImportError("bitsandbytes required")
            return bnb.optim.Lion8bit(params, lr=lr / 10, weight_decay=self.cfg.weight_decay * 10,
                                      betas=(0.95, 0.98))
        if name == "adafactor":
            if not _ADAFACTOR_OK:
                raise ImportError("transformers required for Adafactor")
            return Adafactor(params, scale_parameter=False, relative_step=False,
                             warmup_init=False, weight_decay=1e-3)
        raise ValueError(f"Unknown optimizer: {name!r}")

    # ------------------------------------------------------------------
    def _encode_prompt(self, prompts: list[str]):
        ti = self.tokenizer_one(prompts, padding="max_length",
                                max_length=self.tokenizer_one.model_max_length,
                                truncation=True, return_tensors="pt")
        with torch.no_grad():
            e1 = self.text_encoder_one(ti.input_ids.to(self.accelerator.device))[0]

        ti2 = self.tokenizer_two(prompts, padding="max_length",
                                 max_length=self.tokenizer_two.model_max_length,
                                 truncation=True, return_tensors="pt")
        with torch.no_grad():
            out2 = self.text_encoder_two(ti2.input_ids.to(self.accelerator.device),
                                         output_hidden_states=True)
        return torch.cat([e1, out2.hidden_states[-2]], dim=-1), out2.text_embeds

    # ------------------------------------------------------------------
    def _compute_loss(self, pred, target, timesteps):
        cfg = self.cfg
        if cfg.snr_gamma is None:
            return F.mse_loss(pred.float(), target.float(), reduction="mean")
        snr = compute_snr(self.noise_scheduler, timesteps)
        clamped = torch.stack([snr, cfg.snr_gamma * torch.ones_like(snr)], dim=1).min(dim=1)[0]
        weights = (clamped + 1.0) / (snr + 1.0) if cfg.prediction_type == "v_prediction" else clamped / snr
        loss = F.mse_loss(pred.float(), target.float(), reduction="none")
        return (loss.mean(dim=list(range(1, loss.dim()))) * weights).mean()

    # ------------------------------------------------------------------
    def train(self, dataloader: DataLoader, diagnostics=None):
        cfg = self.cfg
        optimizer = self._build_optimizer()
        lr_scheduler = get_scheduler(
            cfg.lr_scheduler, optimizer=optimizer,
            num_warmup_steps=cfg.lr_warmup_steps,
            num_training_steps=cfg.max_train_steps,
        )

        if cfg.use_ema:
            ema_params = [p for p in self.unet.parameters() if p.requires_grad]
            self.ema = EMAModel(parameters=ema_params, decay=cfg.ema_decay,
                                use_ema_warmup=True, model_cls=UNet2DConditionModel,
                                model_config=self.unet.config)

        self.unet, optimizer, dataloader, lr_scheduler = self.accelerator.prepare(
            self.unet, optimizer, dataloader, lr_scheduler
        )

        global_step = 0
        epochs = max(cfg.max_train_steps // max(len(dataloader), 1), 1)
        print(f"[FullFineTuner] {cfg.max_train_steps} steps over ~{epochs} epochs")

        for epoch in range(epochs):
            self.unet.train()
            for batch in tqdm(dataloader, desc=f"FT Epoch {epoch}", disable=not self.accelerator.is_local_main_process):
                with self.accelerator.accumulate(self.unet):
                    with torch.no_grad():
                        latents = self.vae.encode(
                            batch["pixel_values"].to(dtype=self.vae.dtype)
                        ).latent_dist.sample() * self.vae.config.scaling_factor

                    noise = torch.randn_like(latents)
                    bsz = latents.shape[0]
                    timesteps = torch.randint(
                        0, self.noise_scheduler.config.num_train_timesteps,
                        (bsz,), device=latents.device,
                    ).long()
                    noisy = self.noise_scheduler.add_noise(latents, noise, timesteps)
                    target = (
                        self.noise_scheduler.get_velocity(latents, noise, timesteps)
                        if cfg.prediction_type == "v_prediction" else noise
                    )

                    prompts = batch.get("prompt", [""] * bsz)
                    embeds, pooled = self._encode_prompt(prompts)
                    orig = batch.get("original_size", torch.full((bsz, 2), 1024, device=latents.device))
                    tgt = batch.get("target_size", torch.full((bsz, 2), 1024, device=latents.device))
                    ctl = batch.get("crop_top_left", torch.zeros(bsz, 2, device=latents.device))
                    time_ids = torch.cat([orig, ctl, tgt], dim=-1).to(dtype=embeds.dtype)

                    pred = self.unet(noisy, timesteps, embeds,
                                     added_cond_kwargs={"text_embeds": pooled, "time_ids": time_ids}).sample
                    loss = self._compute_loss(pred, target, timesteps)
                    self.accelerator.backward(loss)
                    optimizer.step()
                    lr_scheduler.step()
                    optimizer.zero_grad()

                    if self.ema is not None:
                        self.ema.step(p for p in self.unet.parameters() if p.requires_grad)

                global_step += 1
                if diagnostics:
                    diagnostics.log_step(global_step, loss=loss.detach().item())

                if global_step % cfg.save_every_n_steps == 0:
                    self._save(global_step)

                if global_step >= cfg.max_train_steps:
                    break
            if global_step >= cfg.max_train_steps:
                break

        self._save(global_step, final=True)

    # ------------------------------------------------------------------
    def _save(self, step: int, final: bool = False):
        tag = "final" if final else f"step{step:07d}"
        out = Path(self.cfg.output_dir) / tag
        out.mkdir(exist_ok=True)
        unwrapped = self.accelerator.unwrap_model(self.unet)
        if self.ema is not None:
            self.ema.store(p for p in unwrapped.parameters() if p.requires_grad)
            self.ema.copy_to(p for p in unwrapped.parameters() if p.requires_grad)
        unwrapped.save_pretrained(str(out))
        if self.ema is not None:
            self.ema.restore(p for p in unwrapped.parameters() if p.requires_grad)
        print(f"[FullFineTuner] Saved {tag} → {out}")
