// AUTO-GENERATED by scripts/generate-nav.mjs from ../mkdocs.yml — do not edit by hand.
export interface NavLeaf {
  title: string;
  kind: "md" | "notebook";
  path: string;
  source: string;
}
export interface NavExternal {
  title: string;
  kind: "external";
  href: string;
}
export interface NavSection {
  title: string;
  kind: "section";
  children: NavNode[];
}
export type NavNode = NavLeaf | NavExternal | NavSection;

export const navTree: NavNode[] = [
  {
    "title": "Home",
    "kind": "md",
    "path": "/",
    "source": "index.md"
  },
  {
    "title": "Getting Started",
    "kind": "section",
    "children": [
      {
        "title": "Quick Start",
        "kind": "md",
        "path": "/readme",
        "source": "readme.md"
      },
      {
        "title": "Architecture",
        "kind": "md",
        "path": "/ARCHITECTURE",
        "source": "ARCHITECTURE.md"
      },
      {
        "title": "C4 Architecture Model",
        "kind": "section",
        "children": [
          {
            "title": "Overview",
            "kind": "md",
            "path": "/STRUCTURIZR",
            "source": "STRUCTURIZR.md"
          },
          {
            "title": "Exporting & Rendering",
            "kind": "md",
            "path": "/structurizr/README",
            "source": "structurizr/README.md"
          }
        ]
      },
      {
        "title": "Troubleshooting",
        "kind": "md",
        "path": "/TROUBLESHOOTING",
        "source": "TROUBLESHOOTING.md"
      }
    ]
  },
  {
    "title": "Tutorials",
    "kind": "section",
    "children": [
      {
        "title": "Overview",
        "kind": "md",
        "path": "/tutorials/index",
        "source": "tutorials/index.md"
      },
      {
        "title": "System Tools",
        "kind": "md",
        "path": "/tutorials/system_tools",
        "source": "tutorials/system_tools.md"
      },
      {
        "title": "Library Database",
        "kind": "md",
        "path": "/tutorials/library_database",
        "source": "tutorials/library_database.md"
      },
      {
        "title": "Web Integration",
        "kind": "md",
        "path": "/tutorials/web_integration",
        "source": "tutorials/web_integration.md"
      },
      {
        "title": "Deep Learning",
        "kind": "md",
        "path": "/tutorials/deep_learning",
        "source": "tutorials/deep_learning.md"
      },
      {
        "title": "Image Stitching",
        "kind": "md",
        "path": "/tutorials/image_stitching",
        "source": "tutorials/image_stitching.md"
      },
      {
        "title": "Typical Workflows",
        "kind": "md",
        "path": "/tutorials/workflows",
        "source": "tutorials/workflows.md"
      },
      {
        "title": "Settings and Login",
        "kind": "md",
        "path": "/tutorials/settings_and_login",
        "source": "tutorials/settings_and_login.md"
      }
    ]
  },
  {
    "title": "Reference",
    "kind": "section",
    "children": [
      {
        "title": "REST API",
        "kind": "md",
        "path": "/api/rest-api",
        "source": "api/rest-api.md"
      },
      {
        "title": "Python API",
        "kind": "section",
        "children": [
          {
            "title": "ASP Pipeline",
            "kind": "md",
            "path": "/api/python/animation",
            "source": "api/python/animation.md"
          },
          {
            "title": "Backend Core",
            "kind": "md",
            "path": "/api/python/core",
            "source": "api/python/core.md"
          },
          {
            "title": "Models",
            "kind": "md",
            "path": "/api/python/models",
            "source": "api/python/models.md"
          }
        ]
      },
      {
        "title": "Rust API",
        "kind": "section",
        "children": [
          {
            "title": "Math Backbone",
            "kind": "md",
            "path": "/api/rust/math",
            "source": "api/rust/math.md"
          }
        ]
      },
      {
        "title": "TypeScript API",
        "kind": "section",
        "children": [
          {
            "title": "Overview",
            "kind": "md",
            "path": "/api/typescript/readme",
            "source": "api/typescript/readme.md"
          }
        ]
      },
      {
        "title": "Kotlin API",
        "kind": "section",
        "children": [
          {
            "title": "Overview",
            "kind": "md",
            "path": "/api/kotlin/index",
            "source": "api/kotlin/index.md"
          }
        ]
      },
      {
        "title": "Python Reference (Sphinx)",
        "kind": "section",
        "children": [
          {
            "title": "Overview",
            "kind": "md",
            "path": "/api/sphinx",
            "source": "api/sphinx.md"
          }
        ]
      }
    ]
  },
  {
    "title": "Notebooks",
    "kind": "section",
    "children": [
      {
        "title": "Benchmark Analysis",
        "kind": "notebook",
        "path": "/notebooks/benchmark_analysis.ipynb",
        "source": "notebooks/benchmark_analysis.ipynb"
      },
      {
        "title": "ASP Pipeline Walkthrough",
        "kind": "notebook",
        "path": "/notebooks/asp_pipeline_walkthrough.ipynb",
        "source": "notebooks/asp_pipeline_walkthrough.ipynb"
      },
      {
        "title": "CLIP Embedding Walkthrough",
        "kind": "notebook",
        "path": "/notebooks/clip_embedding_walkthrough.ipynb",
        "source": "notebooks/clip_embedding_walkthrough.ipynb"
      }
    ]
  },
  {
    "title": "Operations",
    "kind": "section",
    "children": [
      {
        "title": "Benchmarks",
        "kind": "md",
        "path": "/BENCHMARKS",
        "source": "BENCHMARKS.md"
      },
      {
        "title": "Dependency Policy",
        "kind": "md",
        "path": "/DEPENDENCY_POLICY",
        "source": "DEPENDENCY_POLICY.md"
      },
      {
        "title": "Documentation Standards",
        "kind": "md",
        "path": "/DOCUMENTATION_STANDARDS",
        "source": "DOCUMENTATION_STANDARDS.md"
      }
    ]
  },
  {
    "title": "Roadmaps",
    "kind": "section",
    "children": [
      {
        "title": "Master Roadmap",
        "kind": "md",
        "path": "/roadmaps/ROADMAP",
        "source": "roadmaps/ROADMAP.md"
      },
      {
        "title": "Architecture",
        "kind": "md",
        "path": "/roadmaps/architecture",
        "source": "roadmaps/architecture.md"
      },
      {
        "title": "Performance",
        "kind": "md",
        "path": "/roadmaps/performance",
        "source": "roadmaps/performance.md"
      },
      {
        "title": "New Features",
        "kind": "md",
        "path": "/roadmaps/new_features",
        "source": "roadmaps/new_features.md"
      },
      {
        "title": "GUI / UX",
        "kind": "md",
        "path": "/roadmaps/gui_ux",
        "source": "roadmaps/gui_ux.md"
      },
      {
        "title": "Content Generation",
        "kind": "md",
        "path": "/roadmaps/content_generation",
        "source": "roadmaps/content_generation.md"
      },
      {
        "title": "Analytics & Interpretability",
        "kind": "md",
        "path": "/roadmaps/analytics_and_interpretability",
        "source": "roadmaps/analytics_and_interpretability.md"
      },
      {
        "title": "Documentation",
        "kind": "md",
        "path": "/roadmaps/documentation",
        "source": "roadmaps/documentation.md"
      },
      {
        "title": "ASP Pipeline (submodule)",
        "kind": "external",
        "href": "https://acfharbinger.github.io/Anime-Stitch-Pipeline/app/moon/ROADMAP"
      },
      {
        "title": "Manga Colorization & Animation (submodule)",
        "kind": "external",
        "href": "https://acfharbinger.github.io/Cel-Shaded-Generator/app/moon/ROADMAP"
      },
      {
        "title": "Recommendation Engine (submodule)",
        "kind": "external",
        "href": "https://acfharbinger.github.io/Recommendation-Engine/app/moon/ROADMAP"
      }
    ]
  },
  {
    "title": "Research",
    "kind": "section",
    "children": [
      {
        "title": "Analytics & Codebase Visualisation",
        "kind": "md",
        "path": "/research/analytics",
        "source": "research/analytics.md"
      },
      {
        "title": "Image Generation Research",
        "kind": "md",
        "path": "/research/image_generation",
        "source": "research/image_generation.md"
      },
      {
        "title": "ASP Comprehensive Research (submodule)",
        "kind": "external",
        "href": "https://acfharbinger.github.io/Anime-Stitch-Pipeline/app/research/ASP_Comprehensive_Research_Report"
      },
      {
        "title": "Image Stitching Research (submodule)",
        "kind": "external",
        "href": "https://acfharbinger.github.io/Anime-Stitch-Pipeline/app/research/Image_Stitching_Research"
      },
      {
        "title": "Manga & Animation Research (submodule)",
        "kind": "external",
        "href": "https://acfharbinger.github.io/Cel-Shaded-Generator/app/research/Manga%20Colorization%20and%20Animation%20Research"
      },
      {
        "title": "Recommendation Engine Research (submodule)",
        "kind": "external",
        "href": "https://acfharbinger.github.io/Recommendation-Engine/app/research/Building%20a%20Smart%20Recommendation%20Engine"
      }
    ]
  },
  {
    "title": "Submodules",
    "kind": "section",
    "children": [
      {
        "title": "Anime-Stitch-Pipeline",
        "kind": "external",
        "href": "https://acfharbinger.github.io/Anime-Stitch-Pipeline/app/"
      },
      {
        "title": "Cel-Shaded-Generator",
        "kind": "external",
        "href": "https://acfharbinger.github.io/Cel-Shaded-Generator/app/"
      },
      {
        "title": "Recommendation-Engine",
        "kind": "external",
        "href": "https://acfharbinger.github.io/Recommendation-Engine/app/"
      }
    ]
  },
  {
    "title": "Changelog",
    "kind": "md",
    "path": "/CHANGELOG",
    "source": "CHANGELOG.md"
  }
];

export const searchIndex: { title: string; path: string; source: string; kind: "md" | "notebook" }[] = [
  {
    "title": "Home",
    "path": "/",
    "source": "index.md",
    "kind": "md"
  },
  {
    "title": "Quick Start",
    "path": "/readme",
    "source": "readme.md",
    "kind": "md"
  },
  {
    "title": "Architecture",
    "path": "/ARCHITECTURE",
    "source": "ARCHITECTURE.md",
    "kind": "md"
  },
  {
    "title": "Overview",
    "path": "/STRUCTURIZR",
    "source": "STRUCTURIZR.md",
    "kind": "md"
  },
  {
    "title": "Exporting & Rendering",
    "path": "/structurizr/README",
    "source": "structurizr/README.md",
    "kind": "md"
  },
  {
    "title": "Troubleshooting",
    "path": "/TROUBLESHOOTING",
    "source": "TROUBLESHOOTING.md",
    "kind": "md"
  },
  {
    "title": "Overview",
    "path": "/tutorials/index",
    "source": "tutorials/index.md",
    "kind": "md"
  },
  {
    "title": "System Tools",
    "path": "/tutorials/system_tools",
    "source": "tutorials/system_tools.md",
    "kind": "md"
  },
  {
    "title": "Library Database",
    "path": "/tutorials/library_database",
    "source": "tutorials/library_database.md",
    "kind": "md"
  },
  {
    "title": "Web Integration",
    "path": "/tutorials/web_integration",
    "source": "tutorials/web_integration.md",
    "kind": "md"
  },
  {
    "title": "Deep Learning",
    "path": "/tutorials/deep_learning",
    "source": "tutorials/deep_learning.md",
    "kind": "md"
  },
  {
    "title": "Image Stitching",
    "path": "/tutorials/image_stitching",
    "source": "tutorials/image_stitching.md",
    "kind": "md"
  },
  {
    "title": "Typical Workflows",
    "path": "/tutorials/workflows",
    "source": "tutorials/workflows.md",
    "kind": "md"
  },
  {
    "title": "Settings and Login",
    "path": "/tutorials/settings_and_login",
    "source": "tutorials/settings_and_login.md",
    "kind": "md"
  },
  {
    "title": "REST API",
    "path": "/api/rest-api",
    "source": "api/rest-api.md",
    "kind": "md"
  },
  {
    "title": "ASP Pipeline",
    "path": "/api/python/animation",
    "source": "api/python/animation.md",
    "kind": "md"
  },
  {
    "title": "Backend Core",
    "path": "/api/python/core",
    "source": "api/python/core.md",
    "kind": "md"
  },
  {
    "title": "Models",
    "path": "/api/python/models",
    "source": "api/python/models.md",
    "kind": "md"
  },
  {
    "title": "Math Backbone",
    "path": "/api/rust/math",
    "source": "api/rust/math.md",
    "kind": "md"
  },
  {
    "title": "Overview",
    "path": "/api/typescript/readme",
    "source": "api/typescript/readme.md",
    "kind": "md"
  },
  {
    "title": "Overview",
    "path": "/api/kotlin/index",
    "source": "api/kotlin/index.md",
    "kind": "md"
  },
  {
    "title": "Overview",
    "path": "/api/sphinx",
    "source": "api/sphinx.md",
    "kind": "md"
  },
  {
    "title": "Benchmark Analysis",
    "path": "/notebooks/benchmark_analysis.ipynb",
    "source": "notebooks/benchmark_analysis.ipynb",
    "kind": "notebook"
  },
  {
    "title": "ASP Pipeline Walkthrough",
    "path": "/notebooks/asp_pipeline_walkthrough.ipynb",
    "source": "notebooks/asp_pipeline_walkthrough.ipynb",
    "kind": "notebook"
  },
  {
    "title": "CLIP Embedding Walkthrough",
    "path": "/notebooks/clip_embedding_walkthrough.ipynb",
    "source": "notebooks/clip_embedding_walkthrough.ipynb",
    "kind": "notebook"
  },
  {
    "title": "Benchmarks",
    "path": "/BENCHMARKS",
    "source": "BENCHMARKS.md",
    "kind": "md"
  },
  {
    "title": "Dependency Policy",
    "path": "/DEPENDENCY_POLICY",
    "source": "DEPENDENCY_POLICY.md",
    "kind": "md"
  },
  {
    "title": "Documentation Standards",
    "path": "/DOCUMENTATION_STANDARDS",
    "source": "DOCUMENTATION_STANDARDS.md",
    "kind": "md"
  },
  {
    "title": "Master Roadmap",
    "path": "/roadmaps/ROADMAP",
    "source": "roadmaps/ROADMAP.md",
    "kind": "md"
  },
  {
    "title": "Architecture",
    "path": "/roadmaps/architecture",
    "source": "roadmaps/architecture.md",
    "kind": "md"
  },
  {
    "title": "Performance",
    "path": "/roadmaps/performance",
    "source": "roadmaps/performance.md",
    "kind": "md"
  },
  {
    "title": "New Features",
    "path": "/roadmaps/new_features",
    "source": "roadmaps/new_features.md",
    "kind": "md"
  },
  {
    "title": "GUI / UX",
    "path": "/roadmaps/gui_ux",
    "source": "roadmaps/gui_ux.md",
    "kind": "md"
  },
  {
    "title": "Content Generation",
    "path": "/roadmaps/content_generation",
    "source": "roadmaps/content_generation.md",
    "kind": "md"
  },
  {
    "title": "Analytics & Interpretability",
    "path": "/roadmaps/analytics_and_interpretability",
    "source": "roadmaps/analytics_and_interpretability.md",
    "kind": "md"
  },
  {
    "title": "Documentation",
    "path": "/roadmaps/documentation",
    "source": "roadmaps/documentation.md",
    "kind": "md"
  },
  {
    "title": "Analytics & Codebase Visualisation",
    "path": "/research/analytics",
    "source": "research/analytics.md",
    "kind": "md"
  },
  {
    "title": "Image Generation Research",
    "path": "/research/image_generation",
    "source": "research/image_generation.md",
    "kind": "md"
  },
  {
    "title": "Changelog",
    "path": "/CHANGELOG",
    "source": "CHANGELOG.md",
    "kind": "md"
  }
];
