"""Typing-only host protocol for ``AbstractClassTwoGalleries``'s mixins.

Declares the widgets/state/methods each mixin assumes the composed host
class provides -- whether defined by ``AbstractGalleryBase``, by
``manager.AbstractClassTwoGalleries.__init__``, or by a sibling mixin --
so mypy can type-check each mixin file in isolation without false
``attr-defined`` errors. Never instantiated.
"""

from __future__ import annotations

from collections import deque
from typing import Any, Dict, List, Optional, Protocol, Set

from PySide6.QtCore import QThreadPool, QTimer
from PySide6.QtGui import QKeyEvent, QPixmap
from PySide6.QtWidgets import (
    QComboBox,
    QGridLayout,
    QLabel,
    QLineEdit,
    QPushButton,
    QSlider,
    QWidget,
)

from ....components import MarqueeScrollArea
from ....utils.cache.lru_image_cache import LRUImageCache


class AbstractClassTwoGalleriesHostProtocol(Protocol):
    # --- Data state (manager.__init__) ---
    found_files: List[str]
    master_found_files: List[str]
    selected_files: List[str]
    path_to_label_map: Dict[str, QWidget]
    selected_card_map: Dict[str, QWidget]
    _selected_pixmap_cache: LRUImageCache
    _found_pixmap_cache: LRUImageCache
    found_loading_paths: Set[str]
    _loading_paths: Set[str]
    _active_workers: Set[Any]
    _load_generation: int
    thread_pool: QThreadPool

    # --- Pagination state (found/selected galleries) ---
    found_page_size: int
    found_current_page: int
    selected_page_size: int
    selected_current_page: int
    found_pagination_widget: QWidget
    selected_pagination_widget: QWidget
    found_prev_btn: QPushButton
    found_next_btn: QPushButton
    found_page_button: QPushButton
    found_item_range_lbl: QLabel
    found_thumb_slider: QSlider
    found_thumb_size_lbl: QLabel
    selected_prev_btn: QPushButton
    selected_next_btn: QPushButton
    selected_page_button: QPushButton
    selected_item_range_lbl: QLabel
    selected_thumb_slider: QSlider
    selected_thumb_size_lbl: QLabel
    sort_combo: QComboBox
    sort_dir_btn: QPushButton

    # --- Column counts ---
    _current_found_cols: int
    _current_selected_cols: int
    approx_item_width: int
    padding_width: int
    thumbnail_size: int

    # --- UI references ---
    found_gallery_scroll: Optional[MarqueeScrollArea]
    found_gallery_layout: Optional[QGridLayout]
    selected_gallery_scroll: Optional[MarqueeScrollArea]
    selected_gallery_layout: Optional[QGridLayout]
    status_label: Optional[QLabel]
    open_preview_windows: List[QWidget]

    # --- Population timer / sequential loading ---
    _populate_found_timer: QTimer
    _populating_found_index: int
    _paginated_found_paths: List[str]

    # --- Directory history / search ---
    last_browsed_dir: str
    _dir_back_stack: "deque[str]"
    _dir_forward_stack: "deque[str]"
    found_search_input: QLineEdit
    found_search_timer: QTimer
    recent_dirs_limit: int

    # --- Sort/zoom state ---
    _sort_key: str
    _sort_reverse: bool
    _SORT_KEY_MAP: Dict[str, str]
    _scroll_zoom_connected: bool

    # --- Keyboard nav ---
    _focused_found_idx: int
    _selection_anchor_idx: Optional[int]

    # --- Color labels (_color_labels.py) ---
    _LABEL_COLORS: Dict[str, str]
    _LABEL_ICONS: Dict[str, str]

    # --- Cross-mixin / AbstractGalleryBase methods ---
    def create_gallery_label(self, path: str, size: int) -> QLabel: ...
    def create_card_widget(self, path: str, pixmap: Optional[QPixmap], is_selected: bool) -> QWidget: ...
    def update_card_pixmap(self, widget: QWidget, pixmap: Optional[QPixmap]) -> None: ...
    def _update_card_style(self, img_label: QLabel, is_selected: bool) -> None: ...
    def on_selection_changed(self) -> None: ...
    def sender(self) -> Any: ...

    def _apply_sort(self, paths: list) -> list: ...
    def _save_thumbnail_size(self) -> None: ...
    def _on_layout_change(self) -> None: ...
    def _sync_thumb_slider(self) -> None: ...
    def _connect_scroll_zoom(self) -> None: ...
    def _on_ctrl_wheel_zoom(self, delta: int) -> None: ...
    def _on_sort_combo_changed(self, label: str) -> None: ...
    def _on_sort_dir_toggled(self, btn: Any) -> None: ...

    def _add_recent_dir(self, path: str, max_entries: Optional[int] = None) -> None: ...
    def _get_recent_dirs(self) -> list: ...
    def _push_dir_history(self, path: str) -> None: ...
    def _dir_go_back(self) -> Optional[str]: ...
    def _dir_go_forward(self) -> Optional[str]: ...
    def _navigate_to_dir(self, path: str) -> None: ...
    def _generate_contact_sheet(self) -> None: ...

    def update_card_style(self, widget: QWidget, is_selected: bool) -> None: ...
    def select_all_items(self) -> None: ...
    def deselect_all_items(self) -> None: ...
    def invert_selection(self) -> None: ...
    def toggle_selection(self, path: str) -> None: ...

    def is_path_selected(self, path: str) -> bool: ...
    def handle_marquee_selection(self, paths_from_marquee: set, is_ctrl_pressed: bool) -> None: ...
    def reorder_selected(self, dragged_path: str, target_path: str) -> None: ...
    def _replace_path_in_lists(self, old_path: str, new_path: str) -> None: ...
    def _restore_selected_files(self, config: dict) -> None: ...
    def _export_selection_as_paths(self) -> None: ...
    def _copy_selection_to_folder(self) -> None: ...
    def _rename_focused_file(self) -> None: ...
    def _trash_path(self, path: str) -> None: ...

    def create_pagination_controls(self, is_found_gallery: bool) -> QWidget: ...
    def common_create_pagination_ui(self): ...
    def common_update_pagination_state(
        self, total_items: int, page_size: int, current_page: int, controls_dict: dict
    ): ...
    def common_get_paginated_slice(self, full_list: list, page: int, page_size: int) -> list: ...
    def common_calculate_columns(self, scroll_area: Any, approx_width: int) -> int: ...
    def common_reflow_layout(self, layout: Optional[QGridLayout], columns: int) -> None: ...
    def common_filter_string_list(self, full_list: list, query: str) -> list: ...
    def common_create_search_input(self, placeholder_text: str = "") -> QLineEdit: ...
    def common_start_chunked_load(
        self,
        paths: list,
        worker_factory: Any,
        batch_slot: Any = None,
        chunk_size: int = 16,
        max_in_flight: int = 4,
    ) -> None: ...
    def common_show_placeholder(self, layout: Optional[QGridLayout], text: str, columns: int) -> None: ...

    def _change_page(self, delta: int, is_found: bool) -> None: ...
    def _jump_to_page(self, page_index: int, is_found: bool) -> None: ...
    def _on_page_size_changed(self, text: str, is_found: bool) -> None: ...
    def _on_thumb_slider_changed(self, value: int, is_found: bool) -> None: ...
    def _update_pagination_ui(self, is_found: bool, mode: Optional[str] = None) -> None: ...

    def refresh_found_gallery(self) -> None: ...
    def refresh_selected_panel(self) -> None: ...
    def clear_galleries(self, clear_data: Any = True) -> None: ...
    def _clear_layout(self, layout: Optional[QGridLayout]) -> None: ...
    def _load_all_found_page_images(self) -> None: ...
    def _populate_found_step(self) -> None: ...
    def _perform_found_search(self) -> None: ...
    def _get_disk_cache_path(self, video_path: str) -> str: ...
    def _cache_get_as_pixmap(self, path: str) -> Optional[QPixmap]: ...

    def _trigger_batch_found_load(self, paths: List[str]) -> None: ...
    def _trigger_batch_video_found_load(self, paths: List[str]) -> None: ...
    def _trigger_found_load(self, path: str) -> None: ...
    def _trigger_batch_selected_load(self, paths: List[str], widgets: Dict[str, QWidget]) -> None: ...
    def _trigger_priority_load(self, path: str, target_widget: QWidget) -> None: ...
    def _trigger_video_found_load(self, path: str) -> None: ...
    def _on_batch_found_loaded(self, results: List[tuple], requested_paths: List[str]) -> None: ...
    def _on_batch_selected_loaded(self, results: List[tuple], widgets: Dict[str, QWidget]) -> None: ...
    def _on_found_image_loaded(self, path: str, image: Any) -> None: ...
    def _on_selected_image_loaded(self, path: str, image: Any, widget: Optional[QWidget]) -> None: ...
    def start_loading_thumbnails(self, paths: List[str]) -> None: ...

    def _get_color_label(self, path: str) -> Optional[str]: ...
    def _set_color_label(self, path: str, color_key: Optional[str]) -> None: ...
    def _update_found_card_styles(self) -> None: ...

    def _navigate_gallery(self, key: Any) -> None: ...
    def _highlight_focused(self, page_paths: list, idx: int) -> None: ...
    def _preview_focused_item(self) -> None: ...
    def _open_preview_for(self, path: str) -> None: ...
    def _on_found_card_clicked(self, path: str) -> None: ...
    def _on_found_card_right_clicked(self, global_pos: Any, path: str) -> None: ...
    def _recreate_galleries_on_zoom(self) -> None: ...
    def _confirm_deletions_enabled(self) -> bool: ...

    def cancel_loading(self) -> None: ...
    def _save_last_dir(self, path: str, main_win: Any = None) -> None: ...
    def _load_last_dir(self, default: str = "", main_win: Any = None) -> str: ...
    def _show_status(self, message: str, timeout_ms: int = 3000) -> None: ...


    def closeEvent(self, event: Any) -> None: ...
    def jump_to_path(self, path: str) -> bool: ...
    def keyPressEvent(self, event: QKeyEvent) -> None: ...
    def resizeEvent(self, event: Any) -> None: ...
    def update_preview_highlight(self, old_path: str, new_path: str) -> None: ...
    def window(self) -> Any: ...
    def _add_filename_label(self, card: QWidget, path: str) -> None: ...
    _resize_timer: QTimer


__all__ = ["AbstractClassTwoGalleriesHostProtocol"]
