"""Typing-only host protocol for ``AbstractClassSingleGallery``'s mixins.

Declares the widgets/state/methods each mixin assumes the composed host
class provides -- whether defined by ``AbstractGalleryBase``, by
``manager.AbstractClassSingleGallery.__init__``, or by a sibling mixin --
so mypy can type-check each mixin file in isolation without false
``attr-defined`` errors. Never instantiated.
"""

from __future__ import annotations

from collections import deque
from typing import Any, Dict, List, Optional, Protocol, Set, Union

from PySide6.QtCore import QThreadPool, QTimer
from PySide6.QtGui import QImage, QKeyEvent, QPixmap, QResizeEvent
from PySide6.QtWidgets import (
    QComboBox,
    QGridLayout,
    QLabel,
    QLineEdit,
    QPushButton,
    QScrollArea,
    QSlider,
    QWidget,
)

from ....utils.cache.lru_image_cache import LRUImageCache


class AbstractClassSingleGalleryHostProtocol(Protocol):
    # --- Data state (manager.__init__) ---
    gallery_image_paths: List[str]
    master_image_paths: List[str]
    selected_files: List[str]
    path_to_card_widget: Dict[str, QWidget]
    _initial_pixmap_cache: LRUImageCache

    # --- Pagination state ---
    page_size: int
    current_page: int
    pagination_widget: QWidget
    page_combo: QComboBox
    prev_btn: QPushButton
    next_btn: QPushButton
    page_button: QPushButton
    item_range_lbl: QLabel
    thumb_slider: QSlider
    thumb_size_lbl: QLabel
    sort_combo: QComboBox
    sort_dir_btn: QPushButton

    # --- Column / geometry state ---
    _current_cols: int
    _resize_timer: QTimer
    approx_item_width: int
    padding_width: int
    thumbnail_size: int

    # --- Population/loading timer + lazy-loading state ---
    _populate_timer: QTimer
    _paginated_paths: List[str]
    _populating_index: int
    _loading_paths: Set[str]
    _failed_paths: Set[str]
    _active_workers: Set[Any]
    _load_generation: int
    thread_pool: QThreadPool

    # --- Keyboard nav ---
    _focused_idx: int

    # --- UI references ---
    gallery_scroll_area: Optional[QScrollArea]
    gallery_layout: Optional[QGridLayout]

    # --- Directory history / search ---
    last_browsed_scan_dir: str
    _dir_back_stack: "deque[str]"
    _dir_forward_stack: "deque[str]"
    search_input: QLineEdit
    search_debounce_timer: QTimer
    recent_dirs_limit: int

    # --- Sort state (AbstractGalleryBase) ---
    _sort_key: str
    _sort_reverse: bool
    _SORT_KEY_MAP: Dict[str, str]
    _scroll_zoom_connected: bool

    # --- Cross-mixin / AbstractGalleryBase methods ---
    def create_gallery_label(self, path: str, size: int) -> QLabel: ...
    def on_selection_changed(self) -> None: ...
    def sender(self) -> Any: ...

    # Sort/search/zoom (_sort_zoom.py)
    def _apply_sort(self, paths: list) -> list: ...
    def _perform_search(self) -> None: ...
    def _save_thumbnail_size(self) -> None: ...
    def _on_layout_change(self) -> None: ...
    def _sync_thumb_slider(self) -> None: ...

    # Dir history (_dir_history.py)
    def _add_recent_dir(self, path: str, max_entries: Optional[int] = None) -> None: ...
    def _get_recent_dirs(self) -> list: ...

    # Selection (_selection.py)
    def update_card_style(self, widget: QWidget, is_selected: bool) -> None: ...
    def select_all_items(self) -> None: ...
    def deselect_all_items(self) -> None: ...
    def invert_selection(self) -> None: ...
    def toggle_selection(self, path: str) -> None: ...

    # Pagination (_pagination.py)
    def common_create_pagination_ui(self): ...
    def common_update_pagination_state(
        self, total_items: int, page_size: int, current_page: int, controls_dict: dict
    ): ...
    def _on_page_size_changed(self, text: str) -> None: ...
    def _on_thumb_slider_changed(self, value: int) -> None: ...
    def _change_page(self, delta: int) -> None: ...
    def _jump_to_page(self, page_index: int) -> None: ...
    def _update_pagination_ui(self) -> None: ...
    def _on_sort_combo_changed(self, label: str) -> None: ...
    def _on_sort_dir_toggled(self, btn: Any) -> None: ...
    def refresh_gallery_view(self) -> None: ...
    def common_get_paginated_slice(self, full_list: list, page: int, page_size: int) -> list: ...
    def start_loading_gallery(
        self,
        paths: List[str],
        show_progress: bool = True,
        append: bool = False,
        pixmap_cache: Optional[Union[Dict[str, QPixmap], LRUImageCache]] = None,
    ) -> None: ...

    # Inline actions (_inline_actions.py)
    def _export_selection_as_paths(self) -> None: ...
    def _copy_selection_to_folder(self) -> None: ...
    def _rename_selected_file(self) -> None: ...

    # Card rendering (_card_rendering.py)
    def create_card_widget(self, path: str, pixmap: Optional[QPixmap]) -> QWidget: ...
    def update_card_pixmap(
        self, widget: QWidget, pixmap: Optional[QPixmap], label_ref: Optional[QLabel] = None
    ) -> None: ...
    open_preview_windows: List[QWidget]

    # Disk cache (_disk_cache.py)
    def _get_disk_cache_path(self, video_path: str) -> str: ...

    # Loading pipeline (_loading_pipeline.py)
    def common_start_chunked_load(
        self,
        paths: list,
        worker_factory: Any,
        batch_slot: Any = None,
        chunk_size: int = 16,
        max_in_flight: int = 4,
    ) -> None: ...

    # Shared helpers (AbstractGalleryBase)
    def _save_last_dir(self, path: str, main_win: Any = None) -> None: ...
    def _load_last_dir(self, default: str = "", main_win: Any = None) -> str: ...
    def _show_status(self, message: str, timeout_ms: int = 3000) -> None: ...
    def common_create_search_input(self, placeholder_text: str = "") -> QLineEdit: ...
    def common_calculate_columns(self, scroll_area: Any, approx_width: int) -> int: ...
    def common_reflow_layout(self, layout: Optional[QGridLayout], columns: int) -> None: ...
    def common_filter_string_list(self, full_list: list, query: str) -> list: ...
    def jump_to_path(self, path: str) -> bool: ...

    # Lifecycle (_lifecycle.py)
    def cancel_loading(self) -> None: ...
    def clear_gallery_widgets(self) -> None: ...
    def closeEvent(self, event: Any) -> None: ...

    # Loading pipeline extras
    def common_show_placeholder(self, layout: Optional[QGridLayout], text: str, columns: int) -> None: ...
    def calculate_columns(self) -> int: ...
    def _add_filename_label(self, card: QWidget, path: str) -> None: ...


    def _cache_single_loaded_image(self, path: str, q_image: QImage) -> None: ...
    def _connect_scroll_zoom(self) -> None: ...
    def _dir_go_back(self) -> Optional[str]: ...
    def _dir_go_forward(self) -> Optional[str]: ...
    def _generate_error_pixmap(self) -> QPixmap: ...
    def _generate_video_thumbnail(self, path: str) -> Optional[QPixmap]: ...
    def _handle_failed_single_load(self, path: str) -> None: ...
    def _highlight_focused(self, page_paths: list, idx: int) -> None: ...
    def _is_single_load_stale(self, sender: Any) -> bool: ...
    def _load_all_page_images(self) -> None: ...
    def _load_thumbnail_size(self, default: int) -> int: ...
    def _navigate_gallery(self, key: Any) -> None: ...
    def _on_batch_images_loaded(self, results: List[tuple], requested_paths: List[str]) -> None: ...
    def _on_ctrl_wheel_zoom(self, delta: int) -> None: ...
    def _on_single_image_loaded(self, path: str, q_image: QImage) -> None: ...
    def _populate_step(self) -> None: ...
    def _preview_focused_item(self) -> None: ...
    def _push_dir_history(self, path: str) -> None: ...
    def _trigger_batch_found_load(self, paths: List[str]) -> None: ...
    def _trigger_batch_video_load(self, paths: List[str]) -> None: ...
    def _trigger_image_load(self, path: str) -> None: ...
    def _trigger_video_load(self, path: str) -> None: ...
    def create_pagination_controls(self) -> QWidget: ...
    def is_path_selected(self, path: str) -> bool: ...
    def keyPressEvent(self, event: QKeyEvent) -> None: ...
    def resizeEvent(self, event: QResizeEvent) -> None: ...
    def showEvent(self, event: Any) -> None: ...
    def update_preview_highlight(self, old_path: str, new_path: str) -> None: ...



__all__ = ["AbstractClassSingleGalleryHostProtocol"]
