# GUI Test definitions
TEST_MODULES = {
    "base_generative_tab": "models/test_base_generative_tab.py",
    "components": "core/test_components.py",
    "core_helper": "core/test_core_helper.py",
    "core_helper_tasks": "core/test_core_helper_tasks.py",
    "core_tab": "core/test_core_tab.py",
    "login_window": "core/test_login_window.py",
    "main_window": "core/test_main_window.py",
    "settings_window": "core/test_settings_window.py",
    "database_tab": "database/test_database_tab.py",
    "gallery_classes": "image/test_gallery_classes.py",
    "image_helper": "image/test_image_helper.py",
    "image_loader_failure": "image/test_image_loader_failure.py",
    "monitor_columns": "image/test_monitor_columns.py",
    "models_helper": "models/test_models_helper.py",
    "models_tab": "models/test_models_tab.py",
    "video_helper": "video/test_video_helper.py",
    "web_helper": "web/test_web_helper.py",
    "web_tab": "web/test_web_tab.py",
    "canvas_inspector_dialog": "dialogs/test_canvas_inspector_dialog.py",
    "hitl_session_viewer_dialog": "dialogs/test_hitl_session_viewer_dialog.py",
    "seam_diagnostic_dialog": "dialogs/test_seam_diagnostic_dialog.py",
    "stitch_tab": "animation/test_stitch_tab.py",
}
