#!/usr/bin/env python3
"""Export portable theme token JSON to CSS custom properties (#574, #575).

Reads ``gui/src/theming/tokens/{dark,light}.json`` and writes ``:root`` blocks
with ``--it-color-*`` variables for docs website and devtool app surfaces.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
TOKENS_DIR = REPO_ROOT / "gui/src/theming/tokens"
DEFAULT_TOKEN_FILE = TOKENS_DIR / "dark.json"

CSS_VAR_MAP = {
    "accent": "accent",
    "surface": "surface",
    "window_bg": "window-bg",
    "text": "text",
    "muted_text": "muted-text",
    "border": "border",
    "accent_hover": "accent-hover",
    "accent_pressed": "accent-pressed",
}


def _load_tokens(path: Path) -> dict:
    data = json.loads(path.read_text(encoding="utf-8"))
    colors = data.get("colors")
    if not isinstance(colors, dict):
        raise ValueError(f"{path}: missing 'colors' object")
    return colors


def tokens_to_css(colors: dict[str, str], *, surface: str) -> str:
    lines = [
        "/* Generated by tools/dev/theming/export_css_tokens.py — do not edit. */",
        f"/* surface: {surface} */",
        ":root {",
    ]
    for key, css_suffix in CSS_VAR_MAP.items():
        value = colors.get(key)
        if not value:
            raise KeyError(f"Missing color token {key!r}")
        lines.append(f"  --it-color-{css_suffix}: {value};")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_TOKEN_FILE,
        help="Token JSON file (default: gui/src/theming/tokens/dark.json)",
    )
    parser.add_argument(
        "--surface",
        choices=("docs", "dev", "raw"),
        default="raw",
        help="Target surface hint (docs/dev); output format is the same shared token block.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        required=True,
        help="Output CSS file path",
    )
    args = parser.parse_args(argv)

    token_path = args.input if args.input.is_absolute() else REPO_ROOT / args.input
    out_path = args.out if args.out.is_absolute() else REPO_ROOT / args.out

    colors = _load_tokens(token_path)
    css = tokens_to_css(colors, surface=args.surface)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(css, encoding="utf-8")
    try:
        shown = out_path.relative_to(REPO_ROOT)
    except ValueError:
        shown = out_path
    print(f"Wrote {shown} ({len(colors)} tokens)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
