import { useEffect, useMemo, useState } from "react";

/**
 * Loads the dashboard's static, checked-in JSON snapshots
 * (generated by `just dashboard-data` / `scripts/generate-dashboard-data.mjs`).
 *
 * Hard rule (2026-08-10, after a near-miss where a site rewrite briefly
 * deleted the live version of this data): these files under public/data/
 * are live product data during an active rating pass, not placeholders.
 * This hook only reads them — never write-back here.
 */

export interface EvaluationEntry {
  asp?: number;
  simple?: number;
  preference?: string;
  confidence?: number;
  defects?: string[];
  reviewed?: boolean;
  notes?: string;
  updated_at?: string;
}

export interface HumanRatingsSummary {
  schema_version: number;
  generated_at: string;
  source: string;
  summary: {
    total_keys: number;
    reviewed: number;
    mean_asp: number | null;
    mean_simple: number | null;
    preference_counts: Record<string, number>;
    preference_simple_share: number | null;
    narrative_hint: string;
  };
  evaluations: Record<string, EvaluationEntry>;
}

export interface BenchmarkRunSummary {
  total_datasets: number;
  datasets_passed: number;
  datasets_fallback: number;
  total_time_sec: number;
  avg_time_per_dataset_sec: number;
  avg_sharpness_asp: number;
  avg_sharpness_simple: number;
  avg_ghosting_asp: number;
  avg_ghosting_simple: number;
  avg_coverage_asp: number;
  avg_ssim: number;
  verdict_counts: Record<string, number>;
}

export interface BenchmarkRun {
  id: string;
  source: string;
  timestamp: string;
  system?: { gpu?: string | null; cuda?: string | null };
  summary: BenchmarkRunSummary;
}

export interface BenchmarkResults {
  schema_version: number;
  generated_at: string;
  run_count: number;
  runs: BenchmarkRun[];
}

export interface DashboardMeta {
  generated_at: string;
  automated_runs: number;
  human_eval_source: string;
  human_summary: HumanRatingsSummary["summary"];
  notes: string[];
}

interface RatingsData {
  loading: boolean;
  error: string | null;
  humanRatings: HumanRatingsSummary | null;
  benchmarkResults: BenchmarkResults | null;
  meta: DashboardMeta | null;
}

async function fetchJson<T>(path: string): Promise<T | null> {
  try {
    const res = await fetch(path);
    if (!res.ok) return null;
    return (await res.json()) as T;
  } catch {
    return null;
  }
}

export function useRatingsData(): RatingsData {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [humanRatings, setHumanRatings] = useState<HumanRatingsSummary | null>(null);
  const [benchmarkResults, setBenchmarkResults] = useState<BenchmarkResults | null>(null);
  const [meta, setMeta] = useState<DashboardMeta | null>(null);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      const base = import.meta.env.BASE_URL;
      const [hr, br, m] = await Promise.all([
        fetchJson<HumanRatingsSummary>(`${base}data/human_ratings_summary.json`),
        fetchJson<BenchmarkResults>(`${base}data/benchmark_results.json`),
        fetchJson<DashboardMeta>(`${base}data/dashboard_meta.json`),
      ]);
      if (cancelled) return;
      if (!hr && !br && !m) {
        setError("No dashboard data found — run `just dashboard-data` to generate it.");
      }
      setHumanRatings(hr);
      setBenchmarkResults(br);
      setMeta(m);
      setLoading(false);
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  return { loading, error, humanRatings, benchmarkResults, meta };
}

/** Aggregate defect tags across all reviewed evaluations, most common first. */
export function useDefectCounts(evaluations: Record<string, EvaluationEntry> | undefined) {
  return useMemo(() => {
    const counts: Record<string, number> = {};
    for (const entry of Object.values(evaluations ?? {})) {
      for (const defect of entry.defects ?? []) {
        counts[defect] = (counts[defect] ?? 0) + 1;
      }
    }
    return Object.entries(counts).sort((a, b) => b[1] - a[1]);
  }, [evaluations]);
}
