import { useEffect, useMemo, useState } from "react";

/**
 * Loads the dashboard's static, checked-in JSON snapshots
 * (generated by `just dashboard-data` / `scripts/generate-dashboard-data.mjs`).
 *
 * Hard rule (2026-08-10, after a near-miss where a site rewrite briefly
 * deleted the live version of this data): these files under public/data/
 * are live product data during an active rating pass, not placeholders.
 * This hook only reads them — never write-back here.
 */

export interface EvaluationEntry {
  asp?: number;
  simple?: number;
  preference?: string;
  confidence?: number;
  defects?: string[];
  reviewed?: boolean;
  notes?: string;
  updated_at?: string;
}

export interface HumanRatingsSummary {
  schema_version: number;
  generated_at: string;
  source: string;
  summary: {
    total_keys: number;
    reviewed: number;
    mean_asp: number | null;
    mean_simple: number | null;
    preference_counts: Record<string, number>;
    preference_simple_share: number | null;
    narrative_hint: string;
  };
  evaluations: Record<string, EvaluationEntry>;
}

export interface BenchmarkRunSummary {
  total_datasets: number;
  datasets_passed: number;
  datasets_fallback: number;
  total_time_sec: number;
  avg_time_per_dataset_sec: number;
  avg_sharpness_asp: number;
  avg_sharpness_simple: number;
  avg_ghosting_asp: number;
  avg_ghosting_simple: number;
  avg_coverage_asp: number;
  avg_ssim: number;
  verdict_counts: Record<string, number>;
}

export interface BenchmarkRun {
  id: string;
  source: string;
  timestamp: string;
  system?: { gpu?: string | null; cuda?: string | null };
  summary: BenchmarkRunSummary;
}

export interface BenchmarkResults {
  schema_version: number;
  generated_at: string;
  run_count: number;
  runs: BenchmarkRun[];
}

export interface RelabeledCaseEntry {
  case_id: string;
  fallback_code: number;
  fallback_gate: string;
  human_asp_score: number | null;
  human_reviewed: boolean;
  human_simple_score: number | null;
  rated_identity: string;
  true_raw_asp_composite: boolean;
}

export interface M0RelabeledSummary {
  summary: {
    total_cases: number;
    true_raw_asp_composites: {
      count: number;
      mean_human_asp_score: number | null;
    };
    safety_fallbacks_to_scans: {
      count: number;
      mean_human_asp_score: number | null;
      by_gate: Record<string, number>;
    };
  };
  cases: Record<string, RelabeledCaseEntry>;
}

export interface CorrelationCell {
  rho: number | null;
  p_value: number | null;
  n: number;
  diagnosis: "tracks_quality" | "inverse_misleading" | "no_signal" | "insufficient_data";
}

export interface DefectSummaryEntry {
  defect: string;
  label: string;
  count: number;
  prevalence_pct: number;
  mean_asp_score: number;
  mean_simple_score: number;
  stage_id: string;
  stage_name: string;
  category: "structural" | "temporal" | "canvas" | "photometric" | "other";
}

export interface OverallMetricEntry {
  metric_key: string;
  label: string;
  higher_is_better: boolean;
  rho: number | null;
  p_value: number | null;
  n: number;
  diagnosis: "tracks_quality" | "inverse_misleading" | "no_signal" | "insufficient_data";
}

export interface StageGroupEntry {
  stage_id: string;
  stage_name: string;
  category: string;
  defects: string[];
  total_defect_instances: number;
  metrics_avg_rho: Record<string, number | null>;
}

export interface DefectCorrelationMatrix {
  schema_version: number;
  generated_at: string;
  total_reviewed_cases: number;
  metric_catalog: Record<string, { key: string; label: string; higher_is_better: boolean }>;
  overall_corpus_correlation: Record<string, OverallMetricEntry>;
  defect_summaries: Record<string, DefectSummaryEntry>;
  defect_subset_correlation: Record<string, Record<string, CorrelationCell>>;
  defect_detection_correlation: Record<string, Record<string, CorrelationCell>>;
  stage_groups: Record<string, StageGroupEntry>;
}

export interface DashboardMeta {
  generated_at: string;
  automated_runs: number;
  human_eval_source: string;
  human_summary: HumanRatingsSummary["summary"];
  notes: string[];
}

export interface BenchmarkSubsetEntry {
  label: string;
  description: string;
  target_milestone: string;
  cases: string[];
  fidelity: {
    subset_size: number;
    full_corpus_size: number;
    defect_coverage_ratio: number;
    covered_defects_count: number;
    total_defects_count: number;
    mean_asp_score: { subset: number; full: number; abs_error: number };
    mean_simple_score: { subset: number; full: number; abs_error: number };
    preference_distribution: {
      subset: Record<string, number>;
      full: Record<string, number>;
    };
  };
}

export interface BenchmarkSubsetsCatalog {
  schema_version: number;
  generated_at: string;
  total_corpus_cases: number;
  subsets: Record<string, BenchmarkSubsetEntry>;
}

export interface CoherenceV2ABCase {
  name: string;
  target_category: string;
  has_background_corridor: boolean;
  handoff_occurred: boolean;
  metrics_baseline: Record<string, number>;
  metrics_coherence_v2: Record<string, number>;
  delta_metrics: Record<string, number>;
  engineering_verdict: string;
  notes: string;
}

export interface CoherenceV2ABEval {
  schema_version: number;
  generated_at: string;
  total_evaluated_cases: number;
  summary: {
    improved_anatomy_count: number;
    parity_cases_count: number;
    avg_line_art_fracture_reduction: number;
    handoff_rate: number;
  };
  cases: CoherenceV2ABCase[];
}

interface RatingsData {
  loading: boolean;
  error: string | null;
  humanRatings: HumanRatingsSummary | null;
  benchmarkResults: BenchmarkResults | null;
  m0Data: M0RelabeledSummary | null;
  defectCorrelation: DefectCorrelationMatrix | null;
  benchmarkSubsets: BenchmarkSubsetsCatalog | null;
  coherenceV2Eval: CoherenceV2ABEval | null;
  meta: DashboardMeta | null;
}

async function fetchJson<T>(path: string): Promise<T | null> {
  try {
    const res = await fetch(path);
    if (!res.ok) return null;
    return (await res.json()) as T;
  } catch {
    return null;
  }
}

export function useRatingsData(): RatingsData {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [humanRatings, setHumanRatings] = useState<HumanRatingsSummary | null>(null);
  const [benchmarkResults, setBenchmarkResults] = useState<BenchmarkResults | null>(null);
  const [m0Data, setM0Data] = useState<M0RelabeledSummary | null>(null);
  const [defectCorrelation, setDefectCorrelation] = useState<DefectCorrelationMatrix | null>(null);
  const [benchmarkSubsets, setBenchmarkSubsets] = useState<BenchmarkSubsetsCatalog | null>(null);
  const [coherenceV2Eval, setCoherenceV2Eval] = useState<CoherenceV2ABEval | null>(null);
  const [meta, setMeta] = useState<DashboardMeta | null>(null);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      const base = import.meta.env.BASE_URL;
      const [hr, br, m0, dc, bs, ab, m] = await Promise.all([
        fetchJson<HumanRatingsSummary>(`${base}data/human_ratings_summary.json`),
        fetchJson<BenchmarkResults>(`${base}data/benchmark_results.json`),
        fetchJson<M0RelabeledSummary>(`${base}data/m0_relabeled_summary.json`),
        fetchJson<DefectCorrelationMatrix>(`${base}data/defect_correlation_matrix.json`),
        fetchJson<BenchmarkSubsetsCatalog>(`${base}data/benchmark_subsets.json`),
        fetchJson<CoherenceV2ABEval>(`${base}data/coherence_v2_ab_eval.json`),
        fetchJson<DashboardMeta>(`${base}data/dashboard_meta.json`),
      ]);
      if (cancelled) return;
      if (!hr && !br && !m) {
        setError("No dashboard data found — run `just dashboard-data` to generate it.");
      }
      setHumanRatings(hr);
      setBenchmarkResults(br);
      setM0Data(m0);
      setDefectCorrelation(dc);
      setBenchmarkSubsets(bs);
      setCoherenceV2Eval(ab);
      setMeta(m);
      setLoading(false);
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  return { loading, error, humanRatings, benchmarkResults, m0Data, defectCorrelation, benchmarkSubsets, coherenceV2Eval, meta };
}


/** Aggregate defect tags across all reviewed evaluations, most common first. */
export function useDefectCounts(evaluations: Record<string, EvaluationEntry> | undefined) {
  return useMemo(() => {
    const counts: Record<string, number> = {};
    for (const entry of Object.values(evaluations ?? {})) {
      for (const defect of entry.defects ?? []) {
        counts[defect] = (counts[defect] ?? 0) + 1;
      }
    }
    return Object.entries(counts).sort((a, b) => b[1] - a[1]);
  }, [evaluations]);
}
