"""Typing-only host protocol for ``VideoExtractorSubTab``'s mixins.

Declares the widgets/state/methods each mixin assumes the composed host
class provides -- whether defined by ``manager.VideoExtractorSubTab.__init__``,
by ``AbstractClassSingleGallery`` (the tab's real base), or by a sibling
mixin -- so mypy can type-check each mixin file in isolation without false
``attr-defined`` errors. Never instantiated.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Optional, Protocol, Set, Tuple, Union

from PySide6.QtCore import QPoint, QTimer, SignalInstance
from PySide6.QtGui import QImage, QPixmap
from PySide6.QtMultimedia import QAudioOutput, QMediaPlayer
from PySide6.QtMultimediaWidgets import QGraphicsVideoItem
from PySide6.QtWidgets import (
    QCheckBox,
    QComboBox,
    QGraphicsScene,
    QGraphicsView,
    QGridLayout,
    QGroupBox,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QListWidget,
    QProgressBar,
    QProgressDialog,
    QPushButton,
    QScrollArea,
    QSlider,
    QSpinBox,
    QTabBar,
    QTabWidget,
    QVBoxLayout,
    QWidget,
)

from ....classes.image.protos.abstract_class_single_gallery import (
    AbstractClassSingleGalleryHostProtocol,
)
from ....components import ClickableLabel, MarqueeScrollArea, ScrubPreviewPopup
from ....helpers import FrameExtractionWorker
from ....helpers.core.queue_execution_worker import QueueExecutionWorker
from ....helpers.video.storyboard import StoryboardBuilder, StoryboardMeta


class VideoExtractorSubTabHostProtocol(AbstractClassSingleGalleryHostProtocol, Protocol):
    _active_metadata: Optional[dict]
    _audio_output: Optional[QAudioOutput]
    _drag_settle_timer: QTimer
    _extracted_stems_cache: Set[str]
    _extractor_scan_generation: Any
    _is_switching_tabs: bool
    _media_player: Optional[QMediaPlayer]
    _recent_combo_connected: bool
    _scrub_popup: Optional[ScrubPreviewPopup]
    _slider_scrubbing: bool
    _storyboard_builder: Optional[StoryboardBuilder]
    _storyboard_meta: Optional[StoryboardMeta]
    _storyboard_pages: List[QPixmap]
    _subtabs: QTabWidget
    _video_item: Optional[QGraphicsVideoItem]
    active_extraction_worker: Optional[Any]
    active_queue_worker: Optional[QueueExecutionWorker]
    active_videos_config: Dict[str, dict]
    active_videos_tabbar: QTabBar
    available_resolutions: list
    btn_add_cut: QPushButton
    btn_add_tag: QPushButton
    btn_browse: QPushButton
    btn_browse_extract: QPushButton
    btn_cancel_extraction: QPushButton
    btn_clear_cuts: QPushButton
    btn_clear_queue: QPushButton
    btn_clear_tags: QPushButton
    btn_extract_gif: QPushButton
    btn_extract_range: QPushButton
    btn_extract_video: QPushButton
    btn_fullscreen: QPushButton
    btn_jump_end: QPushButton
    btn_jump_start: QPushButton
    btn_load_recent: QPushButton
    btn_play: QPushButton
    btn_process_queue: QPushButton
    btn_set_cut_end: QPushButton
    btn_set_cut_start: QPushButton
    btn_set_end: QPushButton
    btn_set_start: QPushButton
    btn_snapshot: QPushButton
    btn_toggle_mode: QPushButton
    check_extract_vertical: QCheckBox
    check_mute_audio: QCheckBox
    check_player_vertical: QCheckBox
    check_smart_extract: QCheckBox
    combo_engine: QComboBox
    combo_extract_size: QComboBox
    combo_player_speed: QComboBox
    combo_queue_mode: QComboBox
    combo_recent_extractions: QComboBox
    combo_resolution: QComboBox
    combo_smart_method: QComboBox
    combo_speed: QComboBox
    content_widget: QWidget
    current_extracted_paths: List[str]
    cut_end_ms: int
    cut_start_ms: int
    cuts_container: QWidget
    cuts_layout: QHBoxLayout
    cuts_ms: List[Tuple[int, int]]
    cuts_scroll: QScrollArea
    duration_ms: int
    edit_current_time: Optional[QLineEdit]
    end_time_ms: int
    extract_group: QGroupBox
    extraction_dir: Path
    extraction_metadata: Dict[str, Any]
    extraction_progress_bar: QProgressBar
    extraction_queue: List[dict]
    extraction_queue_enabled: bool
    extraction_res_map: dict
    extraction_status_label: QLabel
    extractor_worker: Optional[FrameExtractionWorker]
    gallery_container: QWidget
    graphics_scene: QGraphicsScene
    info_label: QLabel
    last_browsed_extraction_dir: str
    last_browsed_scan_dir: str
    lbl_current_time: Optional[QLabel]
    lbl_total_time: QLabel
    lbl_vol: QLabel
    line_edit_dir: QLineEdit
    line_edit_extract_dir: QLineEdit
    main_layout: QVBoxLayout
    open_preview_windows: List[QWidget]
    pagination_widget: QWidget
    player_container: Optional[QWidget]
    player_inner_layout: QVBoxLayout
    player_layout_container: QVBoxLayout
    progress_dialog: Optional[QProgressDialog]
    queue_group: QGroupBox
    queue_list: QListWidget
    recent_extractions_limit: int
    recent_runs: List[Dict[str, Any]]
    root_layout: QVBoxLayout
    selected_paths: Set[str]
    slider: QSlider
    source_container: QWidget
    source_grid: QGridLayout
    source_group: QGroupBox
    source_path_to_widget: Dict[str, QWidget]
    source_scroll: MarqueeScrollArea
    spin_gif_fps: QSpinBox
    spin_interval: QSpinBox
    start_time_ms: int
    storyboard_progress_bar: QProgressBar
    tab_scroll_area: QScrollArea
    tags_container: QWidget
    tags_layout: QHBoxLayout
    tags_ms: List[Tuple[int, str]]
    tags_scroll: QScrollArea
    time_display_format: str
    use_internal_player: bool
    video_container_widget: QWidget
    video_path: Optional[str]
    video_view: Optional[QGraphicsView]
    volume_slider: QSlider
    wheel_seek_ms: int
    qml_source_path_changed: SignalInstance
    qml_extraction_status: SignalInstance

    def _apply_new_extractions_limit(self) -> None: ...
    def _apply_player_mode(self) -> None: ...
    def _build_cuts_row(self) -> QHBoxLayout: ...
    def _build_directory_section(self) -> None: ...
    def _build_extraction_settings_section(self) -> None: ...
    def _build_player_section(self) -> None: ...
    def _build_results_section(self) -> None: ...
    def _build_tags_row(self) -> QHBoxLayout: ...
    def _cancel_time_edit(self) -> None: ...
    def _clear_gallery(self) -> None: ...
    def _clear_output_gallery(self) -> None: ...
    def _create_source_placeholder_widget(self, path: str) -> QWidget: ...
    def _ensure_scrub_popup(self) -> ScrubPreviewPopup: ...
    def _format_time(self, ms: int) -> str: ...
    def _get_current_extraction_metadata(self) -> dict: ...
    def _get_target_size(self) -> Optional[Union[Tuple[int | str, int | str], str]]: ...
    def _has_extracted_files(self, video_path: str) -> bool: ...
    def _hide_scrub_popup(self) -> None: ...
    def _jump_to_edited_time(self) -> None: ...
    def _jump_to_extraction_end(self, metadata: dict) -> None: ...
    def _jump_to_extraction_start(self, metadata: dict) -> None: ...
    def _load_existing_output_images(self) -> None: ...
    def _load_extraction_history(self) -> None: ...
    def _load_last_extraction_dir(self, default: str) -> str: ...
    def _load_selected_recent_extraction(self) -> None: ...
    def _load_storyboard_cache(self) -> None: ...
    def _load_video_config(self, path: str) -> None: ...
    def _on_active_video_tab_changed(self, index: int) -> None: ...
    def _on_active_video_tab_closed(self, index: int) -> None: ...
    def _on_drag_settled(self) -> None: ...
    def _on_export_error(self, error_msg: str) -> None: ...
    def _on_export_finished(self, new_path: str) -> None: ...
    def _on_extraction_error(self, error_msg: str) -> None: ...
    def _on_extraction_finished(self, new_paths: List[str]) -> None: ...
    def _on_queue_processing_error(self, error_msg: Any) -> None: ...
    def _on_queue_processing_finished(self, results: Any) -> None: ...
    def _on_queue_item_completed(self, index: int, res: dict, item: dict) -> None: ...
    def _on_queue_progress(self, completed: int, total: int) -> None: ...
    def _on_queue_reordered(self) -> None: ...
    def _on_queue_toggle_changed(self) -> None: ...
    def _on_recent_extraction_selected(self, index: int) -> None: ...
    def _on_slider_pressed(self) -> None: ...
    def _on_slider_value_changed(self, position: int) -> None: ...
    def _on_source_scan_batch_finished(self, generation: int) -> None: ...
    def _on_source_video_thumbnail(self, path: str, image: QImage, generation: int) -> None: ...
    def _on_storyboard_failed(self, message: str) -> None: ...
    def _on_storyboard_progress(self, elapsed_ms: int, duration_ms: int) -> None: ...
    def _on_storyboard_ready(self, meta_path: str) -> None: ...
    def _parse_time(self, time_str: str) -> Optional[int]: ...
    def _quick_extract(self, vid_path: Any, ms: Any, out_path: Any) -> None: ...
    def _record_extraction(self, file_paths: List[str], metadata: dict) -> None: ...
    def _refresh_extracted_stems_cache(self) -> None: ...
    def _refresh_source_extracted_indicators(self) -> None: ...
    def _reload_extraction(self, metadata: dict) -> None: ...
    def _run_extraction(self, start: int, end: int, is_range: bool) -> None: ...
    def _run_gif_extraction(self, start: int, end: int) -> None: ...
    def _run_video_extraction(self, start: int, end: int) -> None: ...
    def _save_current_video_config(self) -> None: ...
    def _save_extraction_history(self) -> None: ...
    def _save_last_extraction_dir(self, path: str) -> None: ...
    def _seek_to(self, position_ms: int) -> None: ...
    def _set_extraction_buttons_enabled(self, enabled: bool) -> None: ...
    def _show_tab_context_menu(self, pos: QPoint) -> None: ...
    def _slider_handle_local_pos(self) -> QPoint: ...
    def _start_storyboard(self) -> None: ...
    def _stop_storyboard(self) -> None: ...
    def _style_label(self, label: ClickableLabel, selected: bool) -> None: ...
    def create_gallery_label(self, path: str, size: int) -> ClickableLabel: ...  # type: ignore[override]
    def _update_cuts_label(self) -> None: ...
    def _update_drag_preview(self, position_ms: int) -> None: ...
    def _update_queue_ui(self) -> None: ...
    def _update_range_labels(self) -> None: ...
    def _update_recent_extractions_ui(self) -> None: ...
    def _update_source_label_style(self, path: str, label: ClickableLabel, selected: bool) -> None: ...
    def _update_tags_ui(self) -> None: ...
    def _validate_cut_range(self) -> None: ...
    def _validate_range(self) -> None: ...
    def add_cut(self) -> None: ...
    def add_source_thumbnail(self, path: str, image_or_pixmap: Any) -> None: ...
    def add_tag(self) -> None: ...
    def apply_style(self) -> None: ...
    @property
    def audio_output(self) -> QAudioOutput: ...
    def browse_directory(self) -> None: ...
    def browse_extraction_directory(self) -> None: ...
    def browse_source_qml(self, current_path: Any) -> None: ...
    def cancel_extraction(self, enabled: bool) -> None: ...
    def change_resolution(self, index: int) -> None: ...
    def clear_cuts(self) -> None: ...
    def clear_queue(self) -> None: ...
    def clear_tags(self) -> None: ...
    def delete_cut(self, index: int) -> None: ...
    def delete_image(self, path: str) -> None: ...
    def delete_selected_images(self) -> None: ...
    def delete_tag(self, index: int) -> None: ...
    def duration_changed(self, duration: int) -> None: ...
    def edit_cut_timestamp(self, index: int, is_start: bool) -> None: ...
    def edit_tag(self, index: int) -> None: ...
    def extract_range(self) -> None: ...
    def extract_range_as_gif(self) -> None: ...
    def extract_range_as_video(self) -> None: ...
    def extract_range_qml(self, video_path: Any, start_ms: Any, end_ms: Any, fps: Any) -> None: ...
    def extract_single_frame(self) -> None: ...
    def extract_single_frame_qml(self, video_path: Any, timestamp_ms: Any) -> None: ...
    def fit_video_in_view(self) -> None: ...
    def handle_player_error(self, error: QMediaPlayer.Error, error_string: str) -> None: ...
    def handle_thumbnail_double_click(self, image_path: str) -> None: ...
    def handle_thumbnail_single_click(self, image_path: str) -> None: ...
    def jump_to_cut_time(self, index: int, is_start: bool) -> None: ...
    def jump_to_range_end(self) -> None: ...
    def jump_to_range_start(self) -> None: ...
    def jump_to_tag_time(self, ms: int) -> None: ...
    def load_extraction_config(self, idx: int) -> None: ...
    def load_media(self, file_path: str, force: bool = False) -> None: ...
    def handle_marquee_selection(self, marquee_selection: Set[str], is_ctrl: bool) -> None: ...
    @property
    def media_player(self) -> QMediaPlayer: ...
    def position_changed(self, position: int) -> None: ...
    def process_queue(self) -> None: ...
    def refresh_time_display(self) -> None: ...
    def remove_queue_item(self, idx: int) -> None: ...
    def scan_directory(self, path: str) -> None: ...
    def scan_progress_complete(self) -> None: ...
    def set_cut_end(self) -> None: ...
    def set_cut_start(self) -> None: ...
    def set_position(self, position: int) -> None: ...
    def set_position_on_release(self) -> None: ...
    def set_range_end(self) -> None: ...
    def set_range_start(self) -> None: ...
    def show_cut_context_menu(self, global_pos: QPoint, index: int) -> None: ...
    def show_image_context_menu(self, global_pos: QPoint, path: str) -> None: ...
    def show_queue_context_menu(self, pos: QPoint) -> None: ...
    def show_source_context_menu(self, global_pos: QPoint, path: str) -> None: ...
    def show_tag_context_menu(self, global_pos: QPoint, index: int) -> None: ...
    def show_video_context_menu(self, pos: QPoint) -> None: ...
    def toggle_fullscreen(self) -> None: ...
    def toggle_playback(self) -> None: ...
    def toggle_player_mode(self) -> None: ...
    def update_playback_speed(self, text: str) -> None: ...
    def update_visual_selection(self) -> None: ...
    @property
    def video_item(self) -> QGraphicsVideoItem: ...

    def style(self) -> Any: ...
    def window(self) -> Any: ...


__all__ = ["VideoExtractorSubTabHostProtocol"]
