"""Typing-only host protocol for ``MonitorDisplaySubTab``'s mixins.

Declares the widgets/state/methods each mixin assumes the composed host
class provides -- whether defined by ``manager.MonitorDisplaySubTab.__init__``,
by ``WallpaperCommonBase`` (the tab's real base), or by a sibling mixin --
so mypy can type-check each mixin file in isolation without false
``attr-defined`` errors. Never instantiated.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol, Tuple

from PySide6.QtCore import QPoint, QTimer
from PySide6.QtWidgets import (
    QButtonGroup,
    QComboBox,
    QDoubleSpinBox,
    QGridLayout,
    QGroupBox,
    QLabel,
    QListWidget,
    QPushButton,
    QRadioButton,
    QSpinBox,
    QSplitter,
    QStackedWidget,
    QWidget,
)
from screeninfo import Monitor

from ..wallpaper_tab.graph import WallpaperGraphScene, WallpaperGraphView
from ..wallpaper_tab.graph.data_schema import GraphData, NodeData
from .wallpaper_common_base import WallpaperCommonBaseHostProtocol


class MonitorDisplaySubTabHostProtocol(WallpaperCommonBaseHostProtocol, Protocol):
    # --- Data state (manager.__init__) ---
    _monitors: List[Monitor]
    _graphs: Dict[str, GraphData]
    _current_monitor_id: Optional[str]
    _preview_tmp_dir: Optional[str]
    _queue_durations: Dict[str, List[float]]
    _inapp_active_monitor_id: Optional[str]
    _daemon_active_monitor_id: Optional[str]
    _status_timer: QTimer

    # --- UI widgets built across the *_ui_*/panel mixins ---
    _btn_add_node: QPushButton
    _btn_clear_graph: QPushButton
    _btn_connect: QPushButton
    _btn_daemon_slideshow: QPushButton
    _btn_delete: QPushButton
    _btn_export_queue: QPushButton
    _btn_inapp_slideshow: QPushButton
    _btn_preview: QPushButton
    _btn_self_edge: QPushButton
    _btn_set_start: QPushButton
    _end_color_btn: QPushButton
    _end_color_current: str
    _end_color_preview: QLabel
    _end_combo: QComboBox
    _end_jump_combo: QComboBox
    _placeholder: QLabel
    _props_apply: QPushButton
    _props_bg: QButtonGroup
    _props_dur: QDoubleSpinBox
    _props_dur_row_widget: Any
    _props_edge_add_btn: QPushButton
    _props_edge_repeat_spin: QSpinBox
    _props_edge_target_combo: QComboBox
    _props_edges_grp: Any
    _props_edges_list: QListWidget
    _props_file: QLabel
    _props_hint: QLabel
    _props_mode_grp: Any
    _props_node_id: Optional[str]
    _props_radio_fixed: QRadioButton
    _props_radio_runtime: QRadioButton
    _queue_position_label: QLabel
    _queue_timer_label: QLabel
    _scene: WallpaperGraphScene
    _seq_label: QLabel
    _splitter: QSplitter
    _stack: QStackedWidget
    _view: WallpaperGraphView
    _END_KEYS: List[str]
    scan_thumbnail_widget: QWidget
    scan_thumbnail_layout: QGridLayout

    # --- Cross-mixin methods ---
    def _add_edge(self) -> None: ...
    def _add_node(self) -> None: ...
    def _add_props_edge(self) -> None: ...
    def _add_self_edge(self) -> None: ...
    def _apply_props(self) -> None: ...
    def _build_bottom_toolbar(self, graph_lyt: Any) -> None: ...
    def _build_end_behavior_bar(self) -> QGroupBox: ...
    def _build_gallery_panel(self) -> QGroupBox: ...
    def _build_graph_toolbar(self, graph_lyt: Any) -> None: ...
    def _build_props_panel(self) -> QGroupBox: ...
    def _build_ui(self) -> None: ...
    def _check_daemon_status_on_startup(self) -> None: ...
    def _clear_canvas(self) -> None: ...
    def _current_graph(self) -> Optional[GraphData]: ...
    def _default_entry_duration(self, path: str) -> float: ...
    def _delete_selected(self) -> None: ...
    def _edit_node(self, node_id: str) -> None: ...
    def _export_graph_to_queue(self) -> None: ...
    def _fit_view(self) -> None: ...
    def _generate_preview(self, seq: List[Tuple[str, float]], tmp: str) -> None: ...
    def _on_end_behavior_changed(self, idx: int) -> None: ...
    def _on_graph_changed(self) -> None: ...
    def _on_props_edges_reordered(self) -> None: ...
    def _on_selection_changed(self) -> None: ...
    def _open_file(self, path: str) -> None: ...
    def _persist_current(self) -> None: ...
    def _pick_end_color(self) -> None: ...
    def _populate_props_edges_list(self, node_id: str) -> None: ...
    def _preview_timelapse(self) -> None: ...
    def _props_edges_context_menu(self, pos: QPoint) -> None: ...
    def _read_daemon_status(self) -> Optional[dict]: ...
    def _read_end_behavior_to_graph(self, graph: GraphData) -> None: ...
    def _reconcile_queue_durations(self, monitor_id: str) -> List[float]: ...
    def _refresh_end_color_preview(self) -> None: ...
    def _selected_node_id(self) -> Optional[str]: ...
    def _set_start_node(self) -> None: ...
    def _show_node_in_props(self, nd: NodeData) -> None: ...
    def _start_daemon_slideshow(self, monitor_id: str) -> None: ...
    def _start_inapp_slideshow(self, monitor_id: str) -> None: ...
    def _stop_daemon_slideshow(self) -> None: ...
    def _stop_inapp_slideshow(self) -> None: ...
    def _sync_end_behavior_ui(self, graph: GraphData) -> None: ...
    def _sync_inapp_state_from_native(self, monitor_id: str, status: dict) -> None: ...
    def _toggle_daemon_slideshow(self) -> None: ...
    def _toggle_inapp_slideshow(self) -> None: ...
    def _update_end_jump_combo(self) -> None: ...
    def _update_queue_status_label(self) -> None: ...
    def _update_seq_label(self) -> None: ...
    def _update_slideshow_buttons(self) -> None: ...
    def collect_graphs(self) -> dict: ...
    def do_selection_update(self) -> None: ...
    def restore_graphs(self, data: dict) -> None: ...
    def update_monitors(self, monitors: List[Monitor]) -> None: ...


__all__ = ["MonitorDisplaySubTabHostProtocol"]
