"""Typing-only host protocol for ``SystemDisplaySubTab``'s mixins.

Declares the widgets/state/methods each mixin assumes the composed host
class provides -- whether defined by ``manager.SystemDisplaySubTab.__init__``
(or its class body), by ``WallpaperCommonBase`` (the tab's real base), or by
a sibling mixin -- so mypy can type-check each mixin file in isolation
without false ``attr-defined`` errors. Never instantiated.
"""

from __future__ import annotations

from typing import Any, Dict, Mapping, Optional, Protocol, Tuple, Union

from PySide6.QtCore import QTimer
from PySide6.QtWidgets import (
    QGridLayout,
    QHBoxLayout,
    QLabel,
    QPushButton,
    QWidget,
)

from ....helpers import WallpaperWorker
from .wallpaper_common_base import WallpaperCommonBaseHostProtocol


class SystemDisplaySubTabHostProtocol(WallpaperCommonBaseHostProtocol, Protocol):
    # --- Data state (manager.__init__ / class body) ---
    db_tab_ref: Any
    _scan_dir_restore_timer: QTimer
    _pending_restore_dir: Optional[str]
    wallpaper_style: str
    video_style: str
    time_remaining_sec: int
    interval_sec: int
    countdown_timer: Optional[QTimer]
    current_wallpaper_worker: Optional[WallpaperWorker]
    _wallpaper_worker_serial: int
    _active_wallpaper_worker_serial: Optional[int]
    _wallpaper_worker_completion_relay: Optional[Any]
    _wallpaper_worker_ui_locked: bool

    # --- UI widgets built by _ui_builder.py / _style_selectors.py ---
    # Typed as Any, matching manager.SystemDisplaySubTab's own class-body
    # declarations for these fields (shared names with WallpaperCommonBase/
    # AbstractClassSingleGallery, deliberately loosened there to sidestep
    # the same cross-mixin conflicts these Any types avoid here).
    interval_min_spinbox: Any
    interval_sec_spinbox: Any
    chk_video_runtime_interval: Any
    playback_order_combo: Any
    playback_order_label: Any
    style_combo: Any
    scan_directory_path: Any
    gallery_scroll_area: Any
    gallery_layout: Any
    scan_thumbnail_widget: QWidget
    scan_thumbnail_layout: QGridLayout
    main_scroll_area: Any
    set_wallpaper_btn: Any
    background_type_combo: Any
    style_label: Any
    video_style_combo: Any
    video_style_label: Any
    style_layout_widget: Any
    btn_daemon_toggle: QPushButton
    btn_fetch_current: QPushButton
    btn_skip_wallpapers: QPushButton
    btn_view_logs: QPushButton
    countdown_label: QLabel
    slideshow_group: QWidget
    solid_color_layout: QHBoxLayout
    solid_color_preview: QLabel
    solid_color_widget: QWidget

    # --- Cross-mixin methods ---
    def _apply_vault_slideshow_defaults(self) -> None: ...
    def _build_action_row(self, content_layout: Any) -> None: ...
    def _build_background_type_row(self, settings_layout: Any) -> None: ...
    def _build_gallery_section(self, content_layout: Any) -> None: ...
    def _build_scan_directory_row(self, settings_layout: Any) -> None: ...
    def _build_slideshow_group(self, settings_layout: Any) -> None: ...
    def _build_solid_color_row(self, settings_layout: Any) -> None: ...
    def _build_style_selectors(self, settings_layout: Any) -> None: ...
    def _build_ui(self) -> None: ...
    def _compute_video_runtime_interval_sec(self, monitor_paths: Optional[Dict[str, Optional[str]]]) -> Optional[int]: ...
    def _cycle_slideshow_wallpaper(self, increment: bool) -> None: ...
    def _do_pending_scan_dir_restore(self) -> None: ...
    def _get_daemon_script_path(self) -> Any: ...
    def _get_relevant_styles(self) -> Mapping[str, Optional[Union[str, int, Tuple[str, str]]]]: ...
    def _is_background_daemon_process_alive(self) -> bool: ...
    def _is_daemon_running_config(self) -> bool: ...
    def _daemon_config_running(self) -> bool: ...
    def _on_video_runtime_interval_toggled(self, checked: bool) -> None: ...
    def _start_daemon_countdown_if_active(self) -> None: ...
    def _sync_daemon_config(self) -> None: ...
    def _update_background_type(self, type_name: str) -> None: ...
    def _update_video_style(self, style_name: str) -> None: ...
    def _update_wallpaper_style(self, style_name: str) -> None: ...
    def collect(self) -> dict: ...
    def handle_set_wallpaper_click(self) -> None: ...
    def _handle_wallpaper_worker_finished(self, worker_serial: int, ui_locked: bool, success: bool, message: str) -> None: ...
    def _process_wallpaper_finished(self, success: bool, message: str) -> None: ...
    def handle_wallpaper_status(self, msg: str) -> None: ...
    def lock_ui_for_wallpaper(self) -> None: ...
    def run_wallpaper_worker(self, slideshow_mode: Any = False) -> None: ...
    def select_solid_color(self) -> None: ...
    def skip_current_wallpapers(self) -> None: ...
    def start_slideshow(self) -> None: ...
    def stop_slideshow(self) -> None: ...
    def stop_wallpaper_worker(self) -> None: ...
    def toggle_daemon(self, checked: bool) -> None: ...
    def unlock_ui_for_wallpaper(self) -> None: ...
    def update_countdown(self) -> None: ...
    def view_daemon_logs(self) -> None: ...


__all__ = ["SystemDisplaySubTabHostProtocol"]
