"""Typing-only host protocol for ``WallpaperCommonBase``'s mixins.

Declares the widgets/state/methods each mixin assumes the composed host
class provides -- whether defined by ``manager.WallpaperCommonBase.__init__``
(or its class body, for attributes only ever set by subclasses), by
``AbstractClassSingleGallery`` (the tab's real base), or by a sibling mixin --
so mypy can type-check each mixin file in isolation without false
``attr-defined`` errors. Never instantiated.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol, Tuple

from PySide6.QtCore import QPoint, QTimer
from PySide6.QtGui import QPixmap
from PySide6.QtWidgets import QGroupBox, QMenu
from screeninfo import Monitor

from ....classes.image.protos.abstract_class_single_gallery import (
    AbstractClassSingleGalleryHostProtocol,
)
from ....components import DraggableMonitorContainer, MonitorDropView


class WallpaperCommonBaseHostProtocol(AbstractClassSingleGalleryHostProtocol, Protocol):
    # --- Data state (manager.__init__) ---
    qdbus: Optional[str]
    monitors: List[Monitor]
    monitor_widgets: Dict[str, MonitorDropView]
    monitor_image_paths: Dict[str, Optional[str]]
    monitor_slideshow_queues: Dict[str, List[str]]
    monitor_current_index: Dict[str, int]
    monitor_history: Dict[str, List[str]]
    img_scanner_worker: Optional[Any]
    img_scanner_thread: Optional[Any]
    vid_scanner_worker: Optional[Any]
    vid_scanner_thread: Optional[Any]
    _directory_scan_generation: int
    _directory_scan_state: Any
    _directory_scan_timer: QTimer
    scanned_dir: Any
    path_to_label_map: dict
    _filtering_event: bool
    _system_display_ref: Any
    _current_monitor_id: Any
    linked_tabs: list
    open_image_preview_windows: list
    open_queue_windows: list
    _pagination_debounce_timer: QTimer

    # --- Subclass-specific attributes used in shared methods (per
    # manager.WallpaperCommonBase's own class body) ---
    slideshow_timer: Optional[QTimer]
    current_wallpaper_worker: Optional[Any]
    set_wallpaper_btn: Optional[Any]
    background_type_combo: Optional[Any]
    background_type: str
    solid_color_hex: str
    _graphs: Dict[str, Any]
    _monitor_display_ref: Optional[Any]
    _view: Any
    _scene: Any
    main_scroll_area: Optional[Any]
    scan_directory_path: Optional[Any]
    interval_min_spinbox: Optional[Any]
    style_combo: Optional[Any]

    # --- Cross-mixin state ---
    _pending_scan_request: Any
    _scan_pipeline_busy: bool
    _syncing_selection: bool
    countdown_timer: Any
    monitor_layout_container: DraggableMonitorContainer

    # --- Signals (manager.WallpaperCommonBase class body) ---
    wallpapers_changed: Any
    monitors_updated: Any
    qml_monitors_changed: Any
    qml_status_changed: Any
    directory_scanned: Any
    sync_page_changed: Any
    sync_page_size_changed: Any
    sync_thumb_size_changed: Any
    sync_sort_combo_changed: Any
    sync_sort_dir_changed: Any

    # --- Cross-mixin methods ---
    def _cache_get_thumb(self, path: str) -> Optional[QPixmap]: ...
    def _cancel_directory_scan(self, *, invalidate: bool = True) -> None: ...
    def _change_page(self, delta: int, emit_signal: bool = True) -> None: ...
    def _get_current_system_image_paths_for_all(self) -> Dict[str, Optional[str]]: ...
    def _get_or_generate_thumbnail(self, path: str) -> Optional[QPixmap]: ...
    def _get_rotated_map_for_ui(self, raw_paths: Dict[str, Optional[str]]) -> Dict[str, Optional[str]]: ...
    def _handle_autoscroll(self, global_pos: QPoint) -> None: ...
    def _is_daemon_running_config(self) -> bool: ...
    def _is_slideshow_validation_ready(self) -> Tuple[bool, int]: ...
    def _jump_to_page(self, page_index: int, emit_signal: bool = True) -> None: ...
    def _on_image_scan_finished(self, image_paths: list, _worker: Any = None) -> None: ...
    def _on_monitor_selected(self, monitor_id: Optional[str]) -> None: ...
    def _on_page_size_changed(self, text: str, emit_signal: bool = True) -> None: ...
    def _on_sort_combo_changed(self, label: str, emit_signal: bool = True) -> None: ...
    def _on_sort_dir_toggled(self, btn: Any, emit_signal: bool = True) -> None: ...
    def _on_thumb_slider_changed(self, value: int, emit_signal: bool = True) -> None: ...
    def _on_video_scan_error(self, _worker: Any = None) -> None: ...
    def _on_video_scan_finished(self, video_paths: list, _worker: Any = None) -> None: ...
    def _process_single_drop(self, monitor_id: str, image_path: str) -> None: ...
    def _queued_paths(self) -> list: ...
    def _refresh_gallery_highlights(self) -> None: ...
    def _refresh_open_queue_window(self, monitor_id: str) -> None: ...
    def _scan_pipeline_watchdog(self) -> None: ...
    def _scan_directory_tick(self) -> None: ...
    def _select_monitor(self, monitor_id: Optional[str]) -> None: ...
    def _select_monitor_peer(self, monitor_id: Optional[str]) -> None: ...
    def _set_specific_wallpaper(self, monitor_id: str, path: str, index: Optional[int] = None) -> None: ...
    def _settle_scan_pipeline(self) -> None: ...
    def _start_video_scan(self, directory: str) -> None: ...
    def _stop_scanner_threads(self) -> None: ...
    def _stop_legacy_scanner_threads(self) -> None: ...
    def _stop_vid_scanner_worker(self) -> None: ...
    def _sync_virtual_gallery_marks(self) -> None: ...
    def _update_widget_ui_local(self, monitor_id: str) -> None: ...
    def add_image_to_graph(self, monitor_id: str, path: str) -> None: ...
    def browse_scan_directory(self) -> None: ...
    def cancel_scanning(self) -> None: ...
    def check_all_monitors_set(self) -> None: ...
    def clear_monitor_graph(self, monitor_id: str) -> None: ...
    def clear_monitor_graph_direct(self, monitor_id: str) -> None: ...
    def create_monitor_layout_section(self, title: str) -> QGroupBox: ...
    def display_scan_results(self, image_paths: list) -> None: ...
    def drop_image_qml(self, path: Any) -> None: ...
    def handle_clear_monitor_queue(self, monitor_id: str) -> None: ...
    def handle_delete_image(self, path: str) -> None: ...
    def handle_thumbnail_double_click(self, image_path: str) -> None: ...
    def window(self) -> Any: ...
    def handle_full_image_preview(self, image_path: str) -> None: ...
    def handle_item_swap_request(self, s_mid: str, s_idx: int, t_mid: str, t_idx: int) -> None: ...
    def handle_monitor_double_click(self, monitor_id: str) -> None: ...
    def handle_scan_error(self, message: str, _worker: Any = None) -> None: ...
    def on_image_dropped(self, monitor_id: str, image_path: str) -> None: ...
    def on_images_dropped(self, monitor_id: str, image_paths: list) -> None: ...
    def on_monitor_context_menu(self, monitor_id: str, menu: QMenu) -> None: ...
    def on_queue_reordered(self, monitor_id: str, new_queue: List[str]) -> None: ...
    def populate_monitor_layout(self) -> None: ...
    def populate_scan_image_gallery(self, directory: str, emit_signal: bool = True) -> None: ...
    def remove_closed_win(self) -> None: ...
    def request_monitors_qml(self) -> None: ...
    def set_system_display_ref(self, system_display: Any) -> None: ...
    def set_wallpaper_qml(self, path: Any, monitor_name: Any) -> None: ...
    def show_image_context_menu(self, global_pos: QPoint, path: str) -> None: ...
    def swap_graphs(self, m0: str, m1: str) -> None: ...
    def swap_monitors(self, m0: str, m1: str) -> None: ...
    def sync_update_page(self, page: int) -> None: ...
    def sync_update_page_size(self, text: str) -> None: ...
    def sync_update_sort_combo(self, label: str) -> None: ...
    def sync_update_sort_dir(self, reverse: bool) -> None: ...
    def sync_update_thumb_size(self, value: int) -> None: ...
    def update_monitor_widget_ui(self, monitor_id: str) -> None: ...
    def update_slideshow_settings_qml(self, interval_min: Any, style: Any, random_order: Any, include_subdirs: Any) -> None: ...


__all__ = ["WallpaperCommonBaseHostProtocol"]
