"""Per-pixel seam cost map (character-boundary avoidance) and soft blend weight."""

from __future__ import annotations

from typing import List, Optional

import cv2
import numpy as np

from ._native import BATCH_AVAILABLE, batch


def _apply_exclusion_masks(
    cost: np.ndarray,
    exclusion_masks: Optional[List[np.ndarray]],
    zone_h: int,
    zone_w: int,
) -> np.ndarray:
    if exclusion_masks:
        for em in exclusion_masks:
            if em is None:
                continue
            em_zone = em
            if em.shape != (zone_h, zone_w):
                em_zone = cv2.resize(
                    em, (zone_w, zone_h), interpolation=cv2.INTER_NEAREST
                )
            cost[em_zone > 127] = 1e6
    return cost


def _build_seam_cost_map(
    canvas_zone: np.ndarray,
    bg_mask_a: Optional[np.ndarray],
    bg_mask_b: Optional[np.ndarray],
    dilate_px: int = 15,
    barrier_cost: Optional[float] = None,
    exclusion_masks: Optional[List[np.ndarray]] = None,
) -> np.ndarray:
    if (
        BATCH_AVAILABLE
        and barrier_cost is None
        and not exclusion_masks
        and dilate_px == 15              # C++ uses fixed 15px dilate
    ):
        _all_bg = np.full(canvas_zone.shape[:2], 255, dtype=np.uint8)
        ma = bg_mask_a if bg_mask_a is not None else _all_bg
        mb = bg_mask_b if bg_mask_b is not None else _all_bg
        # cost_map_norm=False: Python fallback never normalizes; keep tiers intact
        return batch.seam.build_seam_cost_map(canvas_zone, ma, mb, cost_map_norm=False)
    """
    P2.4 — Per-pixel seam cost map using character boundary avoidance (§1.6A S19).

    Issue 10A3 — exclusion_masks: list of uint8 (H_zone, W) masks (255=exclude).
    Each mask pixel where value > 127 gets cost=1e6 (hard barrier), forcing the
    DP seam to route around the named region. Generated by
    ``_detect_exclusion_mask(frame, "right arm")`` in grounding.py and injected
    after natural-language seam routing in the HITL MaskReviewDialog.

    Generates high cost near foreground character edges (where BiRefNet says
    the pixel belongs to a character) so the DP seam is routed around them.

    Tiered cost structure — creates a gradient that pulls the DP toward
    background corridors (§1.6A):
      Tier 1 — fg interior: cost = 1.0.  With sem_weight=200 in
      ``_seam_cut()``, every fg-interior pixel costs ≈ 200 energy units vs
      background pixels at ≈ 10–50.  Strongly deters the seam from
      bisecting the character body.
      Tier 2 — dilated fg edge buffer: cost = 0.5 (half of interior).
      Background pixels within ``dilate_px`` of any fg edge pay 100 energy —
      less than interior but more than clean background.  This gradient
      steers the DP THROUGH the edge-buffer zone toward background corridors,
      rather than treating the buffer identically to the body interior.

    Before S19, Tier 2 also used cost=1.0 (same as interior), so the DP had
    no incentive to route through the edge buffer on its way to background.

    If the character fills the full width and there is no all-background path,
    the DP gracefully degrades: it finds the minimum-cost path through the
    character body at its thinnest point.

    Parameters
    ----------
    canvas_zone : (H_zone, W, 3) uint8 slice from the overlap zone.
    bg_mask_a/b : uint8 (H, W) background masks (255=background) for the two frames,
                  already warped to canvas space, sliced to the zone rows.
    dilate_px   : avoidance radius in pixels around foreground edges.
    barrier_cost: cost applied to fg-dominated columns when a background corridor
                  exists (§1.23). *None* → uses module-level `_SEAM_HARD_BARRIER`
                  flag to choose between 2.0 (soft, S33 default) and
                  `_SEAM_HARD_BARRIER_COST` (1e6 hard barrier, S67).

    Returns
    -------
    cost : (H_zone, W) float32 — 0=bg seam-friendly, 0.5=fg edge buffer,
           1.0=fg interior, 2.0=fg-dominated column barrier (§3.15A).
           The column barrier fires only when background-corridor columns exist;
           when every column is fg-dominated the cost stays in {0, 0.5, 1.0}.
    """
    zone_h, zone_w = canvas_zone.shape[:2]
    cost = np.zeros((zone_h, zone_w), dtype=np.float32)

    kernel = cv2.getStructuringElement(
        cv2.MORPH_ELLIPSE, (2 * dilate_px + 1, 2 * dilate_px + 1)
    )
    for bm in (bg_mask_a, bg_mask_b):
        if bm is None:
            continue
        fg = (bm < 127).astype(np.uint8) * 255  # foreground pixels

        # Tier 1 — fg interior: cost=1.0.
        cost = np.maximum(cost, (fg > 0).astype(np.float32))

        # Tier 2 — dilated fg edge buffer: cost=0.5 (§1.6A).
        # np.maximum preserves Tier 1 at 1.0 for fg pixels; only pure-background
        # pixels near fg edges are raised from 0 → 0.5.
        edge = cv2.morphologyEx(
            fg, cv2.MORPH_GRADIENT, cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (3, 3))
        )
        dilated = cv2.dilate(edge, kernel)
        cost = np.maximum(cost, (dilated > 0).astype(np.float32) * 0.5)

    # Tier 1.5 — fg-heavy columns: cost=1.5 (§1.126 FG_MAJORITY_FLOOR)
    zone_fg_frac = (cost >= 1.0).mean()
    if zone_fg_frac > 0.60:
        col_fg_frac = (cost >= 1.0).mean(axis=0)
        heavy = col_fg_frac > 0.80
        if heavy.any() and not heavy.all():
            cost[:, heavy] = np.maximum(cost[:, heavy], 1.5)

    # §3.15A SemanticStitch column barrier (S33) + §1.23 hard barrier upgrade (S67).
    # When a background corridor exists (some but not all columns are fg-dominated),
    # raise the dominated columns to `_barrier` so the DP is steered into the
    # corridor.  Soft mode (S33 default): 2.0 — discourages but does not block.
    # Fallback: when all columns are fg-dominated there is no corridor — skip the
    # filter so the DP finds the minimum-cost through-character path instead.
    _barrier = barrier_cost if barrier_cost is not None else 2.0
    fg_col_frac = (cost >= 1.0).mean(axis=0)
    dominated = fg_col_frac > 0.5
    if dominated.any() and not dominated.all():
        cost[:, dominated] = np.maximum(cost[:, dominated], _barrier)

    # Issue 10A3 — NL seam routing: inject hard-barrier exclusion masks.
    cost = _apply_exclusion_masks(cost, exclusion_masks, zone_h, zone_w)

    return cost


def _soft_seam_weight(
    fa_zone: np.ndarray,
    fb_zone: np.ndarray,
    path_local: np.ndarray,
    zone_h: int,
    W: int,
    sigma: float = 15.0,
    diffuse_sigma: float = 20.0,
    bg_mask_a: Optional[np.ndarray] = None,
    bg_mask_b: Optional[np.ndarray] = None,
) -> np.ndarray:
    """
    P2.5 / S17+S20 — Spatially-adaptive seam blend weight (DSFN technique).

    Returns (zone_h, W) float32 weight in [0, 1]:
      1.0 → fa_zone,  0.0 → fb_zone.

    S17: blend radius is now *per-pixel* rather than per-column-average.
    Each pixel gets a blend ramp proportional to its own local photometric
    similarity: background pixels (high similarity) get a wide, smooth
    transition; foreground pixels (low similarity at character edges) get a
    narrow cut automatically, without any separate fg-mask branch.  This is
    strictly more adaptive than the previous per-column mean — a column
    containing background rows at top and a character edge at the bottom row
    now gives those rows independently-sized ramps instead of the same average.

    S20: when *bg_mask_a* and *bg_mask_b* are provided, fg-vs-fg overlap pixels
    have their diffused similarity zeroed **after** the Gaussian diffusion step.
    This prevents background similarity from bleeding into character-vs-character
    overlap regions through the blur kernel.  Background pixels near the fg
    boundary still receive blended similarity from their neighbours, preserving
    the smooth background→edge gradient; only pixels where BOTH frames classify
    the pixel as foreground are forced to the narrow ramp (min_ramp_bg).
    """
    # Per-pixel L1 distance, mean over channels → (zone_h, W)
    diff = np.abs(fa_zone.astype(np.float32) - fb_zone.astype(np.float32)).mean(axis=2)
    # Similarity field: 1 where frames agree, 0 where they differ strongly
    similarity = np.exp(-diff / max(sigma, 1.0))
    # Anisotropic diffusion: Gaussian blur propagates similarity from flat areas
    sim_diffused = cv2.GaussianBlur(
        similarity, (0, 0), sigmaX=diffuse_sigma, sigmaY=diffuse_sigma
    )
    # S20: zero-out fg-vs-fg pixels *after* diffusion so that background
    # similarity cannot diffuse into character-vs-character overlap regions.
    # bg_mask: True = background pixel.  Only modifies pixels where BOTH frames
    # classify the pixel as foreground; bg-side edge pixels are untouched.
    if bg_mask_a is not None and bg_mask_b is not None:
        both_fg = (~bg_mask_a.astype(bool)) & (~bg_mask_b.astype(bool))
        if both_fg.any():
            sim_diffused[both_fg] = 0.0

    # S17: per-pixel blend ramp — each pixel drives its own transition width.
    # min_ramp_bg (10px) for low-similarity pixels; zone_h * 0.35 for high.
    min_ramp_bg = 10.0
    max_ramp_bg = max(min_ramp_bg + 1.0, zone_h * 0.35)
    ramp = (min_ramp_bg + sim_diffused * (max_ramp_bg - min_ramp_bg)).astype(
        np.float32
    )  # (zone_h, W) — was (1, W) via per-column mean before S17

    ys = np.arange(zone_h, dtype=np.float32)[:, np.newaxis]  # (zone_h, 1)
    seam_y = path_local[np.newaxis, :].astype(np.float32)  # (1, W)
    dist = ys - seam_y  # (zone_h, W)
    weight = np.clip(0.5 - dist / (2.0 * ramp), 0.0, 1.0).astype(np.float32)
    return weight


__all__ = ["_apply_exclusion_masks", "_build_seam_cost_map", "_soft_seam_weight"]
