from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ImageRecordViewSet


# Create a router instance
router = DefaultRouter()
# Register the ImageRecordViewSet with the router. 
# This generates URLs for all CRUD operations.
# The base URL will be /images/
router.register(r'images', ImageRecordViewSet)

# The API URLs are now determined automatically by the router.
urlpatterns = [
    # Include all the URLs generated by the router
    path('', include(router.urls)),
]
