from .convert_tab import ConvertTab
from .database_tab import DatabaseTab
from .delete_tab import DeleteTab
from .image_crawler_tab import ImageCrawlTab
from .merge_tab import MergeTab
from .scan_metadata_tab import ScanMetadataTab
from .search_tab import SearchTab
from .drive_sync_tab import DriveSyncTab
from .wallpaper_tab import WallpaperTab
from .web_requests_tab import WebRequestsTab
from .image_extractor_tab import ImageExtractorTab